// ------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Версия среды выполнения: 16.0.0.0
//  
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторного создания кода.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace TemplateHOG.templates
{
    using System.Linq;
    using System.Text;
    using System.Collections.Generic;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "D:\work\Projects\HOGFW\templates\mho.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "16.0.0.0")]
    public partial class mho : mhoBase
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public virtual string TransformText()
        {
            
            #line 7 "D:\work\Projects\HOGFW\templates\mho.tt"

    if (silhouetteSerial)
        task = true;

	string prg_start = "";
	for (int i = 0; i < prg_start_arr.Length; i++)
	{
		prg_start = "\""+String.Join("\",\"",prg_start_arr)+"\"";
	}

    string path = "assets/levels/level"+(prg=="std"?"":prg)+"/rm_"+rmname+"/zz_"+zzname+"/";

    string objzone = "gfx_"+zzname+"_win_"+mhoname+"_zone";
    string objroot = "obj_"+zzname+"_win_"+mhoname+"_root";
    string taskpanel = "spr_"+zzname+"_win_"+mhoname+"_taskpanel";
	prg = prg == "std"?"":prg;
    
    //silhouetteSerialData
    string silhouetteSerialInputOff = silhouetteSerial?" input=\"0\"":"";


            
            #line default
            #line hidden
            this.Write("zzname = ");
            
            #line 28 "D:\work\Projects\HOGFW\templates\mho.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(zzname));
            
            #line default
            #line hidden
            this.Write("          | без zz_ |\r\nmhoname = ");
            
            #line 29 "D:\work\Projects\HOGFW\templates\mho.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(mhoname));
            
            #line default
            #line hidden
            this.Write("        | без win_ обычно равно имени зз |\r\nrmname = ");
            
            #line 30 "D:\work\Projects\HOGFW\templates\mho.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(rmname));
            
            #line default
            #line hidden
            this.Write("          | без rm_ |\r\nwinitem = ");
            
            #line 31 "D:\work\Projects\HOGFW\templates\mho.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(winitem));
            
            #line default
            #line hidden
            this.Write("        | без get_ |\r\nprg_start = ");
            
            #line 32 "D:\work\Projects\HOGFW\templates\mho.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(prg_start));
            
            #line default
            #line hidden
            this.Write("        | с use_ clk_ |\r\nprg = ");
            
            #line 33 "D:\work\Projects\HOGFW\templates\mho.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(prg));
            
            #line default
            #line hidden
            this.Write("        | текущий прогресс |\r\nzoom = ");
            
            #line 34 "D:\work\Projects\HOGFW\templates\mho.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(zoom));
            
            #line default
            #line hidden
            this.Write("      | in zoomable additional back |\r\ntask = ");
            
            #line 35 "D:\work\Projects\HOGFW\templates\mho.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(task));
            
            #line default
            #line hidden
            this.Write("      | task type else item |\r\nsilhouetteSerial = ");
            
            #line 36 "D:\work\Projects\HOGFW\templates\mho.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(silhouetteSerial));
            
            #line default
            #line hidden
            this.Write("      | silhouette serial |\r\n\r\n");
            
            #line 38 "D:\work\Projects\HOGFW\templates\mho.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(path));
            
            #line default
            #line hidden
            this.Write("         | текущий путь |\r\n");
            
            #line 39 "D:\work\Projects\HOGFW\templates\mho.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(objzone));
            
            #line default
            #line hidden
            this.Write("      | zone |\r\n");
            
            #line 40 "D:\work\Projects\HOGFW\templates\mho.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(objroot));
            
            #line default
            #line hidden
            this.Write("      | root |\r\n");
            
            #line 41 "D:\work\Projects\HOGFW\templates\mho.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(taskpanel));
            
            #line default
            #line hidden
            this.Write("    | taskpanel |\r\n\r\n");
            
            #line 43 "D:\work\Projects\HOGFW\templates\mho.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(silhouetteSerialInputOff));
            
            #line default
            #line hidden
            this.Write(@"
============================================================================================================================================================================
=======xml========== 
ДЛЯ ТАСКОВОЙ ПАНЕЛИ, ЕСЛИ НУЖНО ПОСЛЕ ВСЕХ ТАСКОВ ПОКАЗАТЬ ФИНАЛЬНЫЙ
в PreOpen 

interface.TaskPanelTaskAdd( ho_items, ""mmm"",          1, 0, { { ""spr_billetsext_picklockext"" } } ); --добавили последний таск
interface.TaskPanelShow( ho_items ); 
interface.TaskPanelSetPosTaskByRule( N )  где N сколько тасков без последнего 

в ф-ии проверки включения последнего таска(запускается в прохождении и загрузке), проверяет выполненность всех предыдущх тасков
local task_params = {count = 1, marked=0, name=StringGet(""tsk_billetsext_last"")}
interface.TaskPanelShowTaskLast( task_params )

----
переименовать предмет spr_");
            
            #line 58 "D:\work\Projects\HOGFW\templates\mho.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(zzname));
            
            #line default
            #line hidden
            this.Write("_");
            
            #line 58 "D:\work\Projects\HOGFW\templates\mho.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(winitem));
            
            #line default
            #line hidden
            this.Write(" в spr_");
            
            #line 58 "D:\work\Projects\HOGFW\templates\mho.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(mhoname));
            
            #line default
            #line hidden
            this.Write("_win\r\nзакомментировать прогресс get_");
            
            #line 59 "D:\work\Projects\HOGFW\templates\mho.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(winitem));
            
            #line default
            #line hidden
            this.Write("\r\n\r\nобязательно создать рут obj_");
            
            #line 61 "D:\work\Projects\HOGFW\templates\mho.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(zzname));
            
            #line default
            #line hidden
            this.Write("_win_");
            
            #line 61 "D:\work\Projects\HOGFW\templates\mho.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(mhoname));
            
            #line default
            #line hidden
            this.Write(@"_root, приатачить к нему мхо, анимировать его мгновенно если нужно в preopen, preclose
включить инпут предметам без марка
для анмарков создать пары gfx_firtree_click_aaa, anm_firtree_click_aaa(click_aaa) выключить инпуты
для анмарков прописать в TaskPanelTaskAdd 1 в 4 параметре и доп зону в 5
interface.TaskPanelTaskAdd( ho_items, ""aaa"",  1, 1, { {""spr_""..prg_cutname..""_aaa""}, {""gfx_""..prg_cutname..""_click_aaa""} } );

[[into zz]]

                <obj __type=""obj"" _name=""");
            
            #line 69 "D:\work\Projects\HOGFW\templates\mho.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(objroot));
            
            #line default
            #line hidden
            this.Write("\" active=\"0\" input=\"0\" pos_z=\"100\" visible=\"0\">\r\n");
            
            #line 70 "D:\work\Projects\HOGFW\templates\mho.tt"
 if (silhouetteSerial) {
            
            #line default
            #line hidden
            this.Write("                    <obj __type=\"obj\" _name=\"obj_");
            
            #line 71 "D:\work\Projects\HOGFW\templates\mho.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(zzname));
            
            #line default
            #line hidden
            this.Write("_panel\" croprect_h=\"135\" croprect_init=\"1\" croprect_w=\"131\" croprect_x=\"-68\" crop" +
                    "rect_y=\"-67\" input=\"0\" pos_x=\"-319\" pos_y=\"-176\" pos_z=\"-1\">\r\n                  " +
                    "      <obj __type=\"spr\" _name=\"spr_");
            
            #line 72 "D:\work\Projects\HOGFW\templates\mho.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(zzname));
            
            #line default
            #line hidden
            this.Write("_panel\" input=\"0\" res=\"assets/interface/int_taskpanel/panel\" scale_x=\"-1\" visible" +
                    "=\"0\">\r\n                            <obj __type=\"spr\" _name=\"spr_");
            
            #line 73 "D:\work\Projects\HOGFW\templates\mho.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(zzname));
            
            #line default
            #line hidden
            this.Write("_sh_aaa\" attachtype=\"2\" input=\"0\" res=\"");
            
            #line 73 "D:\work\Projects\HOGFW\templates\mho.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(path));
            
            #line default
            #line hidden
            this.Write("silhouette_aaa\"/>\r\n                            <obj __type=\"spr\" _name=\"spr_");
            
            #line 74 "D:\work\Projects\HOGFW\templates\mho.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(zzname));
            
            #line default
            #line hidden
            this.Write("_sh_bbb\" attachtype=\"2\" input=\"0\" res=\"");
            
            #line 74 "D:\work\Projects\HOGFW\templates\mho.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(path));
            
            #line default
            #line hidden
            this.Write("silhouette_bbb\"/>\r\n                            <obj __type=\"spr\" _name=\"spr_");
            
            #line 75 "D:\work\Projects\HOGFW\templates\mho.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(zzname));
            
            #line default
            #line hidden
            this.Write("_sh_ccc\" attachtype=\"2\" input=\"0\" res=\"");
            
            #line 75 "D:\work\Projects\HOGFW\templates\mho.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(path));
            
            #line default
            #line hidden
            this.Write("silhouette_ccc\"/>\r\n                            <obj __type=\"spr\" _name=\"spr_");
            
            #line 76 "D:\work\Projects\HOGFW\templates\mho.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(zzname));
            
            #line default
            #line hidden
            this.Write("_sh_ddd\" attachtype=\"2\" input=\"0\" res=\"");
            
            #line 76 "D:\work\Projects\HOGFW\templates\mho.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(path));
            
            #line default
            #line hidden
            this.Write("silhouette_ddd\"/>\r\n                            <obj __type=\"spr\" _name=\"spr_");
            
            #line 77 "D:\work\Projects\HOGFW\templates\mho.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(zzname));
            
            #line default
            #line hidden
            this.Write("_sh_eee\" attachtype=\"2\" input=\"0\" res=\"");
            
            #line 77 "D:\work\Projects\HOGFW\templates\mho.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(path));
            
            #line default
            #line hidden
            this.Write("silhouette_eee\"/>\r\n                            <obj __type=\"spr\" _name=\"spr_");
            
            #line 78 "D:\work\Projects\HOGFW\templates\mho.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(zzname));
            
            #line default
            #line hidden
            this.Write("_sh_fff\" attachtype=\"2\" input=\"0\" res=\"");
            
            #line 78 "D:\work\Projects\HOGFW\templates\mho.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(path));
            
            #line default
            #line hidden
            this.Write("silhouette_fff\"/>\r\n                        </obj>\r\n                    </obj>\r\n");
            
            #line 81 "D:\work\Projects\HOGFW\templates\mho.tt"
} 
            
            #line default
            #line hidden
            
            #line 82 "D:\work\Projects\HOGFW\templates\mho.tt"
 if (zoom) {
            
            #line default
            #line hidden
            this.Write("                    <obj __type=\"obj\" _name=\"obj_");
            
            #line 83 "D:\work\Projects\HOGFW\templates\mho.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(zzname));
            
            #line default
            #line hidden
            this.Write("_win_");
            
            #line 83 "D:\work\Projects\HOGFW\templates\mho.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(mhoname));
            
            #line default
            #line hidden
            this.Write("_exit\" pos_z=\"-10\"/>\r\n                    <obj __type=\"obj\" _name=\"obj_");
            
            #line 84 "D:\work\Projects\HOGFW\templates\mho.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(zzname));
            
            #line default
            #line hidden
            this.Write("_win_");
            
            #line 84 "D:\work\Projects\HOGFW\templates\mho.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(mhoname));
            
            #line default
            #line hidden
            this.Write("_exit_block\" pos_z=\"-9\"/>\r\n                    <obj __type=\"spr\" _name=\"spr_");
            
            #line 85 "D:\work\Projects\HOGFW\templates\mho.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(zzname));
            
            #line default
            #line hidden
            this.Write("_back_ho\" input=\"0\" pos_z=\"-8\" res=\"");
            
            #line 85 "D:\work\Projects\HOGFW\templates\mho.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(path));
            
            #line default
            #line hidden
            this.Write("back_ho\"/>  \r\n");
            
            #line 86 "D:\work\Projects\HOGFW\templates\mho.tt"
} 
            
            #line default
            #line hidden
            this.Write("                    <obj __type=\"spr\" _name=\"spr_");
            
            #line 87 "D:\work\Projects\HOGFW\templates\mho.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(zzname));
            
            #line default
            #line hidden
            this.Write("_aaa\" inputrect_h=\"100\" inputrect_init=\"1\" inputrect_w=\"100\" inputrect_x=\"-50\" in" +
                    "putrect_y=\"-50\" pos_x=\"-100\" pos_y=\"-50\" res=\"");
            
            #line 87 "D:\work\Projects\HOGFW\templates\mho.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(path));
            
            #line default
            #line hidden
            this.Write("layers/aaa\"/>\r\n                    <obj __type=\"spr\" _name=\"spr_");
            
            #line 88 "D:\work\Projects\HOGFW\templates\mho.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(zzname));
            
            #line default
            #line hidden
            this.Write("_bbb\"");
            
            #line 88 "D:\work\Projects\HOGFW\templates\mho.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(silhouetteSerialInputOff));
            
            #line default
            #line hidden
            this.Write(" inputrect_h=\"100\" inputrect_init=\"1\" inputrect_w=\"100\" inputrect_x=\"-50\" inputre" +
                    "ct_y=\"-50\" pos_y=\"-50\" res=\"");
            
            #line 88 "D:\work\Projects\HOGFW\templates\mho.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(path));
            
            #line default
            #line hidden
            this.Write("layers/bbb\"/>\r\n                    <obj __type=\"spr\" _name=\"spr_");
            
            #line 89 "D:\work\Projects\HOGFW\templates\mho.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(zzname));
            
            #line default
            #line hidden
            this.Write("_ccc\"");
            
            #line 89 "D:\work\Projects\HOGFW\templates\mho.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(silhouetteSerialInputOff));
            
            #line default
            #line hidden
            this.Write(" inputrect_h=\"100\" inputrect_init=\"1\" inputrect_w=\"100\" inputrect_x=\"-50\" inputre" +
                    "ct_y=\"-50\" pos_x=\"100\" pos_y=\"-50\" res=\"");
            
            #line 89 "D:\work\Projects\HOGFW\templates\mho.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(path));
            
            #line default
            #line hidden
            this.Write("layers/ccc\"/>\r\n                    <obj __type=\"spr\" _name=\"spr_");
            
            #line 90 "D:\work\Projects\HOGFW\templates\mho.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(zzname));
            
            #line default
            #line hidden
            this.Write("_ddd\"");
            
            #line 90 "D:\work\Projects\HOGFW\templates\mho.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(silhouetteSerialInputOff));
            
            #line default
            #line hidden
            this.Write(" inputrect_h=\"100\" inputrect_init=\"1\" inputrect_w=\"100\" inputrect_x=\"-50\" inputre" +
                    "ct_y=\"-50\" pos_x=\"-100\" pos_y=\"50\" res=\"");
            
            #line 90 "D:\work\Projects\HOGFW\templates\mho.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(path));
            
            #line default
            #line hidden
            this.Write("layers/ddd\"/>\r\n                    <obj __type=\"spr\" _name=\"spr_");
            
            #line 91 "D:\work\Projects\HOGFW\templates\mho.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(zzname));
            
            #line default
            #line hidden
            this.Write("_eee\"");
            
            #line 91 "D:\work\Projects\HOGFW\templates\mho.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(silhouetteSerialInputOff));
            
            #line default
            #line hidden
            this.Write(" inputrect_h=\"100\" inputrect_init=\"1\" inputrect_w=\"100\" inputrect_x=\"-50\" inputre" +
                    "ct_y=\"-50\" pos_y=\"50\" res=\"");
            
            #line 91 "D:\work\Projects\HOGFW\templates\mho.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(path));
            
            #line default
            #line hidden
            this.Write("layers/eee\"/>\r\n                    <obj __type=\"spr\" _name=\"spr_");
            
            #line 92 "D:\work\Projects\HOGFW\templates\mho.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(zzname));
            
            #line default
            #line hidden
            this.Write("_fff\"");
            
            #line 92 "D:\work\Projects\HOGFW\templates\mho.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(silhouetteSerialInputOff));
            
            #line default
            #line hidden
            this.Write(" inputrect_h=\"100\" inputrect_init=\"1\" inputrect_w=\"100\" inputrect_x=\"-50\" inputre" +
                    "ct_y=\"-50\" pos_x=\"100\" pos_y=\"50\" res=\"");
            
            #line 92 "D:\work\Projects\HOGFW\templates\mho.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(path));
            
            #line default
            #line hidden
            this.Write("layers/fff\"/>\r\n                </obj>\r\n\r\n=======lua==========\r\n\r\n==");
            
            #line 97 "D:\work\Projects\HOGFW\templates\mho.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(prg_start));
            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 98 "D:\work\Projects\HOGFW\templates\mho.tt"
 foreach (var progress in prg_start_arr) {
            
            #line default
            #line hidden
            this.Write("==");
            
            #line 99 "D:\work\Projects\HOGFW\templates\mho.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(progress));
            
            #line default
            #line hidden
            this.Write("\r\n\r\nprivate.");
            
            #line 101 "D:\work\Projects\HOGFW\templates\mho.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(progress));
            
            #line default
            #line hidden
            this.Write("_end = function()\r\n");
            
            #line 102 "D:\work\Projects\HOGFW\templates\mho.tt"
 if (prg_start_arr.Length > 1) {
            
            #line default
            #line hidden
            this.Write("  if ld.CheckRequirements( {");
            
            #line 103 "D:\work\Projects\HOGFW\templates\mho.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(prg_start));
            
            #line default
            #line hidden
            this.Write("} ) then\r\n");
            
            #line 104 "D:\work\Projects\HOGFW\templates\mho.tt"
} 
            
            #line default
            #line hidden
            
            #line 105 "D:\work\Projects\HOGFW\templates\mho.tt"
 if (zoom) {
            
            #line default
            #line hidden
            this.Write("  local zzRect = ld.Quick.GetInputRect(512,512)\r\n  local exitBorder = 50\r\n  ObjSe" +
                    "t( \"obj_");
            
            #line 108 "D:\work\Projects\HOGFW\templates\mho.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(zzname));
            
            #line default
            #line hidden
            this.Write("_win_");
            
            #line 108 "D:\work\Projects\HOGFW\templates\mho.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(mhoname));
            
            #line default
            #line hidden
            this.Write("_exit_block\", ld.Quick.GetInputRect(zzRect.inputrect_w - 2*exitBorder, zzRect.inp" +
                    "utrect_h - 2*exitBorder)  );\r\n  ObjSet( \"obj_");
            
            #line 109 "D:\work\Projects\HOGFW\templates\mho.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(zzname));
            
            #line default
            #line hidden
            this.Write("_win_");
            
            #line 109 "D:\work\Projects\HOGFW\templates\mho.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(mhoname));
            
            #line default
            #line hidden
            this.Write("_exit\", zzRect );\r\n  ObjSet( \"obj_");
            
            #line 110 "D:\work\Projects\HOGFW\templates\mho.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(zzname));
            
            #line default
            #line hidden
            this.Write("_win_");
            
            #line 110 "D:\work\Projects\HOGFW\templates\mho.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(mhoname));
            
            #line default
            #line hidden
            this.Write("_exit\", {\r\n    event_mdown = function() private.PreClose_");
            
            #line 111 "D:\work\Projects\HOGFW\templates\mho.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(mhoname));
            
            #line default
            #line hidden
            this.Write("() end;\r\n    event_menter = function() ld.ShCur(CURSOR_DOWN) end;\r\n    event_mlea" +
                    "ve = function() ld.ShCur(CURSOR_DEFAULT) end;\r\n  } );\r\n  ObjSet( \"gfx_");
            
            #line 115 "D:\work\Projects\HOGFW\templates\mho.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(zzname));
            
            #line default
            #line hidden
            this.Write("_win_");
            
            #line 115 "D:\work\Projects\HOGFW\templates\mho.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(mhoname));
            
            #line default
            #line hidden
            this.Write("_zone\", {event_mdown = function() \r\n    private.PreOpen_");
            
            #line 116 "D:\work\Projects\HOGFW\templates\mho.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(mhoname));
            
            #line default
            #line hidden
            this.Write("() \r\n  end} );\r\n");
            
            #line 118 "D:\work\Projects\HOGFW\templates\mho.tt"
} 
            
            #line default
            #line hidden
            
            #line 119 "D:\work\Projects\HOGFW\templates\mho.tt"
 if (prg_start_arr.Length > 1) {
            
            #line default
            #line hidden
            this.Write("  end\r\n");
            
            #line 121 "D:\work\Projects\HOGFW\templates\mho.tt"
} 
            
            #line default
            #line hidden
            this.Write("  ld.SubRoom.Complete( \"");
            
            #line 122 "D:\work\Projects\HOGFW\templates\mho.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(progress));
            
            #line default
            #line hidden
            this.Write("\" )\r\nend;\r\n\r\n==func_end ");
            
            #line 125 "D:\work\Projects\HOGFW\templates\mho.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(progress));
            
            #line default
            #line hidden
            this.Write("\r\n\r\n  local func_end = function()\r\n");
            
            #line 128 "D:\work\Projects\HOGFW\templates\mho.tt"
 if (prg_start_arr.Length > 1) {
            
            #line default
            #line hidden
            this.Write("    if ld.CheckRequirements( {");
            
            #line 129 "D:\work\Projects\HOGFW\templates\mho.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(prg_start));
            
            #line default
            #line hidden
            this.Write("} ) then\r\n");
            
            #line 130 "D:\work\Projects\HOGFW\templates\mho.tt"
} 
            
            #line default
            #line hidden
            this.Write("    private.PreOpen_");
            
            #line 131 "D:\work\Projects\HOGFW\templates\mho.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(mhoname));
            
            #line default
            #line hidden
            this.Write("() \r\n");
            
            #line 132 "D:\work\Projects\HOGFW\templates\mho.tt"
 if (prg_start_arr.Length > 1) {
            
            #line default
            #line hidden
            this.Write("    else\r\n      ld.Lock(0)    \r\n    end\r\n");
            
            #line 136 "D:\work\Projects\HOGFW\templates\mho.tt"
} 
            
            #line default
            #line hidden
            this.Write("  end\r\n\r\n");
            
            #line 139 "D:\work\Projects\HOGFW\templates\mho.tt"
 }//end foreach
            
            #line default
            #line hidden
            this.Write("\r\n==========miniHO \r\n\r\nprivate.win_");
            
            #line 143 "D:\work\Projects\HOGFW\templates\mho.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(mhoname));
            
            #line default
            #line hidden
            this.Write("_logic = function()\r\n  if ld.CheckRequirements( {\"win_");
            
            #line 144 "D:\work\Projects\HOGFW\templates\mho.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(mhoname));
            
            #line default
            #line hidden
            this.Write("\"} ) then\r\n    interface.InventoryItemAdd(\"inv_");
            
            #line 145 "D:\work\Projects\HOGFW\templates\mho.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(winitem));
            
            #line default
            #line hidden
            this.Write("\",\"spr_");
            
            #line 145 "D:\work\Projects\HOGFW\templates\mho.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(zzname));
            
            #line default
            #line hidden
            this.Write("_win\");\r\n  end  \r\nend;\r\ncmn.AddSubscriber( \"win_");
            
            #line 148 "D:\work\Projects\HOGFW\templates\mho.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(mhoname));
            
            #line default
            #line hidden
            this.Write("\", private.win_");
            
            #line 148 "D:\work\Projects\HOGFW\templates\mho.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(mhoname));
            
            #line default
            #line hidden
            this.Write("_logic );\r\n\r\nprivate.win_");
            
            #line 150 "D:\work\Projects\HOGFW\templates\mho.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(mhoname));
            
            #line default
            #line hidden
            this.Write("_load = function() \r\n  local gm = private.mho[ \"win_");
            
            #line 151 "D:\work\Projects\HOGFW\templates\mho.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(mhoname));
            
            #line default
            #line hidden
            this.Write("\" ];\r\n  gm.unmark_load()\r\n  if not ld.CheckRequirements( {\"win_");
            
            #line 153 "D:\work\Projects\HOGFW\templates\mho.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(mhoname));
            
            #line default
            #line hidden
            this.Write("\"} ) then\r\n    common_impl.ProcessHoStart(\"");
            
            #line 154 "D:\work\Projects\HOGFW\templates\mho.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(mhoname));
            
            #line default
            #line hidden
            this.Write("\",\"delete_objects\"\r\n");
            
            #line 155 "D:\work\Projects\HOGFW\templates\mho.tt"
 if (silhouetteSerial) {
            
            #line default
            #line hidden
            this.Write("    , function(key, obj) gm.complete_load(key) end --obj only for tasks\r\n");
            
            #line 157 "D:\work\Projects\HOGFW\templates\mho.tt"
} else {
            
            #line default
            #line hidden
            this.Write("    --, function(key, obj) ld.LogTrace(key, obj) if key == \"aaa\" then ld.LogTrace" +
                    "( \"WAY1\" ); ObjDelete(\"anm_snowgirlzz_anm_aaa\") end end --obj only for tasks\r\n");
            
            #line 159 "D:\work\Projects\HOGFW\templates\mho.tt"
} 
            
            #line default
            #line hidden
            this.Write("      )\r\n    --common_impl.ProcessHoStart(\"");
            
            #line 161 "D:\work\Projects\HOGFW\templates\mho.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(mhoname));
            
            #line default
            #line hidden
            this.Write("\",\"no_delete_objects\"\r\n    --, function(key, obj) gm.complete_load(key) end --obj" +
                    " only for tasks\r\n    --  )\r\n  else\r\n    gm.complete_load()\r\n    ObjDelete(\"gfx_");
            
            #line 166 "D:\work\Projects\HOGFW\templates\mho.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(zzname));
            
            #line default
            #line hidden
            this.Write("_win_");
            
            #line 166 "D:\work\Projects\HOGFW\templates\mho.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(mhoname));
            
            #line default
            #line hidden
            this.Write("_zone\")\r\n  end;\r\n  ld.SubRoom.Complete( \"win_");
            
            #line 168 "D:\work\Projects\HOGFW\templates\mho.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(mhoname));
            
            #line default
            #line hidden
            this.Write("\" )\r\nend\r\ncmn.AddSubscriber( \"win_");
            
            #line 170 "D:\work\Projects\HOGFW\templates\mho.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(mhoname));
            
            #line default
            #line hidden
            this.Write("\", private.win_");
            
            #line 170 "D:\work\Projects\HOGFW\templates\mho.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(mhoname));
            
            #line default
            #line hidden
            this.Write("_load, private.room_objname ); \r\n\r\n=V========= function public.win_");
            
            #line 172 "D:\work\Projects\HOGFW\templates\mho.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(mhoname));
            
            #line default
            #line hidden
            this.Write("()\r\n\r\nlocal func_end = function()\r\n  cmn.SetEventDone( \"win_");
            
            #line 175 "D:\work\Projects\HOGFW\templates\mho.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(mhoname));
            
            #line default
            #line hidden
            this.Write("\" );\r\n  cmn.CallEventHandler( \"win_");
            
            #line 176 "D:\work\Projects\HOGFW\templates\mho.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(mhoname));
            
            #line default
            #line hidden
            this.Write("\" );\r\n  private.PreClose_");
            
            #line 177 "D:\work\Projects\HOGFW\templates\mho.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(mhoname));
            
            #line default
            #line hidden
            this.Write("()\r\n  ld.Lock(0);\r\n  SoundHoTheme( false );\r\nend;\r\n\r\n==========\r\nfunction private" +
                    ".InitMHO_");
            
            #line 183 "D:\work\Projects\HOGFW\templates\mho.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(mhoname));
            
            #line default
            #line hidden
            this.Write("()\r\n  local prg_name = \"win_");
            
            #line 184 "D:\work\Projects\HOGFW\templates\mho.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(mhoname));
            
            #line default
            #line hidden
            this.Write(@"""
  local prg_cutname = prg_name:gsub(""^win_"", """")
  local zz_name = common_impl.hint[ prg_name ].zz
  local zz_cutname = zz_name:gsub(""^zz_"", """")
  local rm_name = common_impl.hint[ prg_name ].room
  local root = ""obj_""..zz_cutname..""_""..prg_name..""_root""
");
            
            #line 190 "D:\work\Projects\HOGFW\templates\mho.tt"
 if (silhouetteSerial) {
            
            #line default
            #line hidden
            this.Write("  local hided = \"\"\r\n  local panel = \"spr_\"..zz_cutname..\"_panel\"\r\n  local panel_r" +
                    "oot = \"obj_\"..zz_cutname..\"_panel\"\r\n");
            
            #line 194 "D:\work\Projects\HOGFW\templates\mho.tt"
} 
            
            #line default
            #line hidden
            this.Write("  local prg_req = {");
            
            #line 195 "D:\work\Projects\HOGFW\templates\mho.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(prg_start));
            
            #line default
            #line hidden
            this.Write(@"}
  if not private.mho then private.mho = {} end
  if not private.mho[ prg_name ] then private.mho[ prg_name ] = {} end
  local gm = private.mho[prg_name];
  local marked = {} --{""eee"", ""fff""}
  gm.abc = {""aaa"", ""bbb"", ""ccc"", ""ddd"", ""eee"", ""fff""}
  gm.key2index = {aaa=1, bbb=2, ccc=3, ddd=4, eee=5, fff=6}
  gm.N = #gm.abc;
  gm.get_spr = function(n) return string.format(""spr_%s_%s"", zz_cutname, n) end ;
  gm.get_sh = function(n) return string.format(""spr_%s_%s_sh"", zz_cutname, n) end ;
");
            
            #line 205 "D:\work\Projects\HOGFW\templates\mho.tt"
 if (silhouetteSerial) {
            
            #line default
            #line hidden
            this.Write("  gm.get_sil = function(n) return string.format(\"spr_%s_sh_%s\", zz_cutname, n) en" +
                    "d ;\r\n");
            
            #line 207 "D:\work\Projects\HOGFW\templates\mho.tt"
} 
            
            #line default
            #line hidden
            this.Write("\r\n  gm.names = {}\r\n  for n=1,gm.N do\r\n    gm.names[ gm.abc[n] ] =  gm.get_spr( gm" +
                    ".abc[n] )\r\n");
            
            #line 212 "D:\work\Projects\HOGFW\templates\mho.tt"
 if (silhouetteSerial) {
            
            #line default
            #line hidden
            this.Write("    if n ~= 1 then\r\n      ObjSet( gm.get_spr( gm.abc[n] ), {input = 0} );\r\n      " +
                    "ObjSet( gm.get_sil( gm.abc[n] ), {visible = 0} );\r\n    end\r\n");
            
            #line 217 "D:\work\Projects\HOGFW\templates\mho.tt"
} 
            
            #line default
            #line hidden
            this.Write(@"  end;

  function gm.unmark(o)
    ObjDelete(""gfx_""..zz_cutname..""_click_""..o) 
    ObjSet( ""anm_""..zz_cutname..""_click_""..o, {animfunc = ""click_""..o, frame = 999 } );
    if not ld.CheckRequirements({prg_name}) then
      if not cmn.IsFoundTask(prg_cutname,o) then
        ObjSet( ""spr_""..zz_cutname..""_""..o, {active = 1, input = 1, visible = 1} );  
      end
    end
  end

  function gm.unmark_load()
    for i,o in ipairs(marked) do
      if ld.CheckRequirements({prg_name}) or cmn.IsUnmarkedTask(prg_cutname,o) then
        gm.unmark(o)
      end
    end
  end

");
            
            #line 238 "D:\work\Projects\HOGFW\templates\mho.tt"
 if (silhouetteSerial) {
            
            #line default
            #line hidden
            this.Write(@"  function gm.update_task(key, time)
    local nextKey = gm.abc[gm.key2index[key]+1]
    ObjSet( gm.get_spr( nextKey ), {input = 1} );
    ObjSet( gm.get_sil( nextKey ), {visible = 1, alp = 0} );
    ld.Anim.Set( gm.get_sil( nextKey ), {alp = 1}, time)
    if key == gm.abc[#gm.abc] then
      ld.Anim.Set( panel, {alp = 0}, time)
    end
  end

");
            
            #line 249 "D:\work\Projects\HOGFW\templates\mho.tt"
} 
            
            #line default
            #line hidden
            this.Write(@"  function gm.complete_load(oneKey)
    if not gm.isInit then --проверка чтобы не сработало при нормальном выигрыше
      for key,obj in pairs(gm.names) do
        if not oneKey or key == oneKey then
          ObjDelete( gm.get_spr( key ) )
          ObjDelete( gm.get_sh( key ) )
");
            
            #line 256 "D:\work\Projects\HOGFW\templates\mho.tt"
 if (silhouetteSerial) {
            
            #line default
            #line hidden
            this.Write("          ObjDelete( gm.get_sil( key ) )\r\n          gm.update_task( key )\r\n");
            
            #line 259 "D:\work\Projects\HOGFW\templates\mho.tt"
} 
            
            #line default
            #line hidden
            this.Write("          --ObjDelete(\"obj_");
            
            #line 260 "D:\work\Projects\HOGFW\templates\mho.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(mhoname));
            
            #line default
            #line hidden
            this.Write("_win_");
            
            #line 260 "D:\work\Projects\HOGFW\templates\mho.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(mhoname));
            
            #line default
            #line hidden
            this.Write("_\"..key..\"_zone\")\r\n          --ObjSet( \"anm_");
            
            #line 261 "D:\work\Projects\HOGFW\templates\mho.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(mhoname));
            
            #line default
            #line hidden
            this.Write("_\"..key, {animfunc = key, frame = 999 } );\r\n          --if key == \"ccc\" then\r\n   " +
                    "       --  ObjSet( \"anm_");
            
            #line 263 "D:\work\Projects\HOGFW\templates\mho.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(mhoname));
            
            #line default
            #line hidden
            this.Write("_some_\"..key, {visible = 1} );\r\n          --end\r\n        end\r\n      end;\r\n    end" +
                    "\r\n  end\r\n\r\n  function private.PreOpen_");
            
            #line 270 "D:\work\Projects\HOGFW\templates\mho.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(mhoname));
            
            #line default
            #line hidden
            this.Write(@"()

    if ld.CheckRequirements( {prg_name} ) or not ld.CheckRequirements(prg_req) then
      return
    end;

    function gm.init()
      if gm.isInit then return else gm.isInit = true; end;


      for key,obj in pairs(gm.names) do
        local options = { event_mdown = function() 
          --если предметы в рутах с нулеывыми координатами(например анимтаги)
          --ObjSet( obj, ld.Quick.GetPos( obj, zz_name, zz_name ) );
          --ObjAttach( obj, zz_name )
");
            
            #line 285 "D:\work\Projects\HOGFW\templates\mho.tt"
 if (task) {
            
            #line default
            #line hidden
            this.Write("          --cmn.HoTaskFind( obj, nil, true, 100 ) -- 2 param for mul objects(cuts" +
                    " name), 4 param set pos_z\r\n          cmn.HoTaskFind( obj, key, true ) \r\n");
            
            #line 288 "D:\work\Projects\HOGFW\templates\mho.tt"
} else {
            
            #line default
            #line hidden
            this.Write("          cmn.HoItemFind( obj, \"itm_\"..prg_cutname..\"_\"..key );\r\n");
            
            #line 290 "D:\work\Projects\HOGFW\templates\mho.tt"
} 
            
            #line default
            #line hidden
            this.Write("          ld.FxBlickAnmObj(obj,true)\r\n          ObjAnimate( obj, 8, 0, 0, functio" +
                    "n() end, {0,3,1, 0.3,3,0} );\r\n          ObjDelete( gm.get_sh( key ) )\r\n");
            
            #line 294 "D:\work\Projects\HOGFW\templates\mho.tt"
 if (silhouetteSerial) {
            
            #line default
            #line hidden
            this.Write("          ObjDelete( gm.get_sil( key ) )\r\n          gm.update_task(key, 0.5)\r\n");
            
            #line 297 "D:\work\Projects\HOGFW\templates\mho.tt"
} 
            
            #line default
            #line hidden
            this.Write(@"        end }
        ObjSet( obj, options );
      end;

      for i,o in ipairs(marked) do
        ObjSet( ""gfx_""..zz_cutname..""_click_""..o, {
          event_mdown = function()
            ObjDelete(""gfx_""..zz_cutname..""_click_""..o)
            ld.AnimPlay( ""anm_""..zz_cutname..""_click_""..o, ""click_""..o, 
            function()  
              cmn.UnmarkTask( prg_cutname, o );
              gm.unmark(o)
            end ) 
          end;
          event_menter = function() ld.ShCur(CURSOR_HAND) end;
          event_mleave = function() ld.ShCur(CURSOR_DEFAULT) end;
        } );
      end

");
            
            #line 317 "D:\work\Projects\HOGFW\templates\mho.tt"
 if (task) {
} else {
            
            #line default
            #line hidden
            this.Write(@"      local panel = ""obj_""..prg_cutname..""_items""
      ObjCreate(panel, ""obj"")
      for n=1,#gm.abc do
        local key = gm.abc[n]
        local obj = ""itm_""..prg_cutname..""_""..key
        ObjCreate(obj,""spr"")
        ObjSet(obj, {input=0, res=""assets/levels/level");
            
            #line 325 "D:\work\Projects\HOGFW\templates\mho.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(prg));
            
            #line default
            #line hidden
            this.Write("/rm_");
            
            #line 325 "D:\work\Projects\HOGFW\templates\mho.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(rmname));
            
            #line default
            #line hidden
            this.Write("/zz_");
            
            #line 325 "D:\work\Projects\HOGFW\templates\mho.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(zzname));
            
            #line default
            #line hidden
            this.Write("/layers/\"..key..\"_cont\"})\r\n        ObjAttach(obj,panel)\r\n      end;\r\n");
            
            #line 328 "D:\work\Projects\HOGFW\templates\mho.tt"
} 
            
            #line default
            #line hidden
            this.Write("    end;\r\n\r\n    gm.init();\r\n\r\n    public.mini_ho = prg_cutname\r\n");
            
            #line 334 "D:\work\Projects\HOGFW\templates\mho.tt"
 if (task) {
            
            #line default
            #line hidden
            this.Write("    common_impl.hint[ \"win_");
            
            #line 335 "D:\work\Projects\HOGFW\templates\mho.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(mhoname));
            
            #line default
            #line hidden
            this.Write("\" ].customhint = interface.TaskPanelHoHintShow\r\n");
            
            #line 336 "D:\work\Projects\HOGFW\templates\mho.tt"
} else {
            
            #line default
            #line hidden
            this.Write("    common_impl.hint[ \"win_");
            
            #line 337 "D:\work\Projects\HOGFW\templates\mho.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(mhoname));
            
            #line default
            #line hidden
            this.Write("\" ].customhint = interface.ItemPanelHoHintShow\r\n");
            
            #line 338 "D:\work\Projects\HOGFW\templates\mho.tt"
} 
            
            #line default
            #line hidden
            this.Write("\r\n    if cmn.InitHo( prg_cutname ) then\r\n      for i,o in ipairs(marked) do\r\n    " +
                    "    cmn.SetMarkedTask( prg_cutname, o );\r\n      end\r\n    end\r\n\r\n    local ho_ite" +
                    "ms = {};\r\n");
            
            #line 347 "D:\work\Projects\HOGFW\templates\mho.tt"
 if (task) {
            
            #line default
            #line hidden
            this.Write(@"    interface.TaskPanelTaskAdd( ho_items, ""aaa"",  1, 0, { { ""spr_""..prg_cutname..""_aaa""} } );
    interface.TaskPanelTaskAdd( ho_items, ""bbb"",  1, 0, { { ""spr_""..prg_cutname..""_bbb""} } );
    interface.TaskPanelTaskAdd( ho_items, ""ccc"",  1, 0, { { ""spr_""..prg_cutname..""_ccc""} } );
    interface.TaskPanelTaskAdd( ho_items, ""ddd"",  1, 0, { { ""spr_""..prg_cutname..""_ddd""} } );
    interface.TaskPanelTaskAdd( ho_items, ""eee"",  1, 0, { { ""spr_""..prg_cutname..""_eee""} } );
    interface.TaskPanelTaskAdd( ho_items, ""fff"",  1, 0, { { ""spr_""..prg_cutname..""_fff""} } );
    interface.TaskPanelShow( ho_items,prg_cutname );
");
            
            #line 355 "D:\work\Projects\HOGFW\templates\mho.tt"
 if (silhouetteSerial) {
            
            #line default
            #line hidden
            this.Write("    local task_params = {count = 1, marked=0, name=StringGet(\"tsk_\"..prg_cutname." +
                    ".\"_last\")}\r\n    interface.TaskPanelShowTaskLast( task_params )\r\n");
            
            #line 358 "D:\work\Projects\HOGFW\templates\mho.tt"
} 
            
            #line default
            #line hidden
            
            #line 359 "D:\work\Projects\HOGFW\templates\mho.tt"
} else {
            
            #line default
            #line hidden
            this.Write(@"    interface.ItemPanelItemAdd( ho_items, ""aaa"", { ""spr_""..prg_cutname..""_aaa""}  );
    interface.ItemPanelItemAdd( ho_items, ""bbb"", { ""spr_""..prg_cutname..""_bbb""}  );
    interface.ItemPanelItemAdd( ho_items, ""ccc"", { ""spr_""..prg_cutname..""_ccc""}  );
    interface.ItemPanelItemAdd( ho_items, ""ddd"", { ""spr_""..prg_cutname..""_ddd""}  );
    interface.ItemPanelItemAdd( ho_items, ""eee"", { ""spr_""..prg_cutname..""_eee""}  );
    interface.ItemPanelItemAdd( ho_items, ""fff"", { ""spr_""..prg_cutname..""_fff""}  );
    interface.ItemPanelShow( ho_items );
");
            
            #line 367 "D:\work\Projects\HOGFW\templates\mho.tt"
} 
            
            #line default
            #line hidden
            this.Write("    SoundHoTheme( true );\r\n\r\n    gm.unmark_load()\r\n    ObjSet( root, {active = 1," +
                    " input = 1, visible = 1} );\r\n\r\n    ld.Lock(1)\r\n    ObjAnimate( root, 8, 0, 0, fu" +
                    "nction() ld.Lock(0) end, {0,0,0, 0.5,0,1} );\r\n");
            
            #line 375 "D:\work\Projects\HOGFW\templates\mho.tt"
 if (silhouetteSerial) {
            
            #line default
            #line hidden
            this.Write("    ObjSet( panel, {visible = 1} );\r\n    ObjAttach( panel_root, \"obj_int_frame_su" +
                    "broom_grids\" )\r\n    ObjAnimate( panel, 0, 0, 0, function() end, {0,0,126, 0.5,0," +
                    "0} );\r\n    --ObjAnimate( hided, 8, 0, 0, function()  end, {0,0,1, 0.5,0,0} );\r\n");
            
            #line 380 "D:\work\Projects\HOGFW\templates\mho.tt"
} 
            
            #line default
            #line hidden
            this.Write("\r\n    --uncomment if needed custom win(without window)\r\n    --common_impl.DialogH" +
                    "o_Show_Custom = function()\r\n    --  public.win_");
            
            #line 384 "D:\work\Projects\HOGFW\templates\mho.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(mhoname));
            
            #line default
            #line hidden
            this.Write("()\r\n    --end\r\n  end;\r\n\r\n  function private.PreClose_");
            
            #line 388 "D:\work\Projects\HOGFW\templates\mho.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(mhoname));
            
            #line default
            #line hidden
            this.Write("(fast)\r\n    if ObjGet(root).input then\r\n      if fast then\r\n        ObjAnimate( \"" +
                    "rm_");
            
            #line 391 "D:\work\Projects\HOGFW\templates\mho.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(rmname));
            
            #line default
            #line hidden
            this.Write("\", 7, 0, 0, function() \r\n          ObjSet( root, {active = 0, input = 0, visible " +
                    "= 0} );\r\n");
            
            #line 393 "D:\work\Projects\HOGFW\templates\mho.tt"
 if (silhouetteSerial) {
            
            #line default
            #line hidden
            this.Write("          ObjSet( panel, { pos_x = 126 } );\r\n          ObjDetach( panel_root )\r\n " +
                    "         --ObjAnimate( hided, 8, 0, 0, function()  end, {0,0,1} );\r\n");
            
            #line 397 "D:\work\Projects\HOGFW\templates\mho.tt"
} 
            
            #line default
            #line hidden
            this.Write("        end, {0,0,0} );\r\n      else\r\n        ld.Lock(1)\r\n        ObjAnimate( root" +
                    ", 8, 0, 0, function() \r\n          ObjSet( root, {active = 0, input = 0, visible " +
                    "= 0} );\r\n          ld.Lock(0)\r\n        end, {0,0,1, 0.5,0,0} );\r\n");
            
            #line 405 "D:\work\Projects\HOGFW\templates\mho.tt"
 if (silhouetteSerial) {
            
            #line default
            #line hidden
            this.Write("        --ObjAnimate( hided, 8, 0, 0, function()  end, {0,0,0, 0.5,0,1} );\r\n     " +
                    "   ObjAnimate( panel, 0, 0, 0, function() ObjDetach( panel_root ) end, {0,0,0, 0" +
                    ".5,0,126} );\r\n");
            
            #line 408 "D:\work\Projects\HOGFW\templates\mho.tt"
} 
            
            #line default
            #line hidden
            this.Write("      end\r\n      if ld.CheckRequirements( prg_req ) and not ld.CheckRequirements(" +
                    " {prg_name} ) then\r\n        SoundHoTheme( false );\r\n");
            
            #line 412 "D:\work\Projects\HOGFW\templates\mho.tt"
 if (task) {
            
            #line default
            #line hidden
            this.Write("        interface.TaskPanelHide();\r\n");
            
            #line 414 "D:\work\Projects\HOGFW\templates\mho.tt"
} else {
            
            #line default
            #line hidden
            this.Write("        interface.ItemPanelHide();\r\n");
            
            #line 416 "D:\work\Projects\HOGFW\templates\mho.tt"
} 
            
            #line default
            #line hidden
            this.Write("      end;\r\n      public.mini_ho = nil;\r\n      common_impl.hint[ prg_name ].custo" +
                    "mhint = nil;\r\n    end\r\n    common_impl.DialogHo_Show_Custom = nil\r\n  end;\r\nend\r\n" +
                    "private.InitMHO_");
            
            #line 424 "D:\work\Projects\HOGFW\templates\mho.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(mhoname));
            
            #line default
            #line hidden
            this.Write("()\r\n\r\n=V=========\r\n\r\n  function zz_");
            
            #line 428 "D:\work\Projects\HOGFW\templates\mho.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(zzname));
            
            #line default
            #line hidden
            this.Write(".Open()\r\n  end\r\n  function zz_");
            
            #line 430 "D:\work\Projects\HOGFW\templates\mho.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(zzname));
            
            #line default
            #line hidden
            this.Write(".PreOpen()\r\n");
            
            #line 431 "D:\work\Projects\HOGFW\templates\mho.tt"
 if (zoom) {
            
            #line default
            #line hidden
            this.Write("    --private.PreOpen_");
            
            #line 432 "D:\work\Projects\HOGFW\templates\mho.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(mhoname));
            
            #line default
            #line hidden
            this.Write("()\r\n");
            
            #line 433 "D:\work\Projects\HOGFW\templates\mho.tt"
} else {
            
            #line default
            #line hidden
            this.Write("    private.PreOpen_");
            
            #line 434 "D:\work\Projects\HOGFW\templates\mho.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(mhoname));
            
            #line default
            #line hidden
            this.Write("()\r\n");
            
            #line 435 "D:\work\Projects\HOGFW\templates\mho.tt"
} 
            
            #line default
            #line hidden
            this.Write("  end\r\n  function zz_");
            
            #line 437 "D:\work\Projects\HOGFW\templates\mho.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(zzname));
            
            #line default
            #line hidden
            this.Write(".PreClose()\r\n    private.PreClose_");
            
            #line 438 "D:\work\Projects\HOGFW\templates\mho.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(mhoname));
            
            #line default
            #line hidden
            this.Write("(\"fast\")\r\n  end\r\n  function zz_");
            
            #line 440 "D:\work\Projects\HOGFW\templates\mho.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(zzname));
            
            #line default
            #line hidden
            this.Write(".Close()\r\n  end;\r\n");
            return this.GenerationEnvironment.ToString();
        }
        
        #line 1 "D:\work\Projects\HOGFW\templates\t4helper.tt"

    void NeedComment(string message, bool comments)
    {
        Selector(comments,message,"");
        
        #line default
        #line hidden
        
        #line 5 "D:\work\Projects\HOGFW\templates\t4helper.tt"
}
    void Selector(bool selector, string messageTrue, string messageFalse)
    {
        string message = selector?messageTrue:messageFalse;
		if (message != "") {

        
        #line default
        #line hidden
        
        #line 10 "D:\work\Projects\HOGFW\templates\t4helper.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(message));

        
        #line default
        #line hidden
        
        #line 10 "D:\work\Projects\HOGFW\templates\t4helper.tt"

	}
}
        
        #line default
        #line hidden
    }
    
    #line default
    #line hidden
    #region Base class
    /// <summary>
    /// Base class for this transformation
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "16.0.0.0")]
    public class mhoBase
    {
        #region Fields
        private global::System.Text.StringBuilder generationEnvironmentField;
        private global::System.CodeDom.Compiler.CompilerErrorCollection errorsField;
        private global::System.Collections.Generic.List<int> indentLengthsField;
        private string currentIndentField = "";
        private bool endsWithNewline;
        private global::System.Collections.Generic.IDictionary<string, object> sessionField;
        #endregion
        #region Properties
        /// <summary>
        /// The string builder that generation-time code is using to assemble generated output
        /// </summary>
        protected System.Text.StringBuilder GenerationEnvironment
        {
            get
            {
                if ((this.generationEnvironmentField == null))
                {
                    this.generationEnvironmentField = new global::System.Text.StringBuilder();
                }
                return this.generationEnvironmentField;
            }
            set
            {
                this.generationEnvironmentField = value;
            }
        }
        /// <summary>
        /// The error collection for the generation process
        /// </summary>
        public System.CodeDom.Compiler.CompilerErrorCollection Errors
        {
            get
            {
                if ((this.errorsField == null))
                {
                    this.errorsField = new global::System.CodeDom.Compiler.CompilerErrorCollection();
                }
                return this.errorsField;
            }
        }
        /// <summary>
        /// A list of the lengths of each indent that was added with PushIndent
        /// </summary>
        private System.Collections.Generic.List<int> indentLengths
        {
            get
            {
                if ((this.indentLengthsField == null))
                {
                    this.indentLengthsField = new global::System.Collections.Generic.List<int>();
                }
                return this.indentLengthsField;
            }
        }
        /// <summary>
        /// Gets the current indent we use when adding lines to the output
        /// </summary>
        public string CurrentIndent
        {
            get
            {
                return this.currentIndentField;
            }
        }
        /// <summary>
        /// Current transformation session
        /// </summary>
        public virtual global::System.Collections.Generic.IDictionary<string, object> Session
        {
            get
            {
                return this.sessionField;
            }
            set
            {
                this.sessionField = value;
            }
        }
        #endregion
        #region Transform-time helpers
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void Write(string textToAppend)
        {
            if (string.IsNullOrEmpty(textToAppend))
            {
                return;
            }
            // If we're starting off, or if the previous text ended with a newline,
            // we have to append the current indent first.
            if (((this.GenerationEnvironment.Length == 0) 
                        || this.endsWithNewline))
            {
                this.GenerationEnvironment.Append(this.currentIndentField);
                this.endsWithNewline = false;
            }
            // Check if the current text ends with a newline
            if (textToAppend.EndsWith(global::System.Environment.NewLine, global::System.StringComparison.CurrentCulture))
            {
                this.endsWithNewline = true;
            }
            // This is an optimization. If the current indent is "", then we don't have to do any
            // of the more complex stuff further down.
            if ((this.currentIndentField.Length == 0))
            {
                this.GenerationEnvironment.Append(textToAppend);
                return;
            }
            // Everywhere there is a newline in the text, add an indent after it
            textToAppend = textToAppend.Replace(global::System.Environment.NewLine, (global::System.Environment.NewLine + this.currentIndentField));
            // If the text ends with a newline, then we should strip off the indent added at the very end
            // because the appropriate indent will be added when the next time Write() is called
            if (this.endsWithNewline)
            {
                this.GenerationEnvironment.Append(textToAppend, 0, (textToAppend.Length - this.currentIndentField.Length));
            }
            else
            {
                this.GenerationEnvironment.Append(textToAppend);
            }
        }
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void WriteLine(string textToAppend)
        {
            this.Write(textToAppend);
            this.GenerationEnvironment.AppendLine();
            this.endsWithNewline = true;
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void Write(string format, params object[] args)
        {
            this.Write(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void WriteLine(string format, params object[] args)
        {
            this.WriteLine(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Raise an error
        /// </summary>
        public void Error(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Raise a warning
        /// </summary>
        public void Warning(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            error.IsWarning = true;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Increase the indent
        /// </summary>
        public void PushIndent(string indent)
        {
            if ((indent == null))
            {
                throw new global::System.ArgumentNullException("indent");
            }
            this.currentIndentField = (this.currentIndentField + indent);
            this.indentLengths.Add(indent.Length);
        }
        /// <summary>
        /// Remove the last indent that was added with PushIndent
        /// </summary>
        public string PopIndent()
        {
            string returnValue = "";
            if ((this.indentLengths.Count > 0))
            {
                int indentLength = this.indentLengths[(this.indentLengths.Count - 1)];
                this.indentLengths.RemoveAt((this.indentLengths.Count - 1));
                if ((indentLength > 0))
                {
                    returnValue = this.currentIndentField.Substring((this.currentIndentField.Length - indentLength));
                    this.currentIndentField = this.currentIndentField.Remove((this.currentIndentField.Length - indentLength));
                }
            }
            return returnValue;
        }
        /// <summary>
        /// Remove any indentation
        /// </summary>
        public void ClearIndent()
        {
            this.indentLengths.Clear();
            this.currentIndentField = "";
        }
        #endregion
        #region ToString Helpers
        /// <summary>
        /// Utility class to produce culture-oriented representation of an object as a string.
        /// </summary>
        public class ToStringInstanceHelper
        {
            private System.IFormatProvider formatProviderField  = global::System.Globalization.CultureInfo.InvariantCulture;
            /// <summary>
            /// Gets or sets format provider to be used by ToStringWithCulture method.
            /// </summary>
            public System.IFormatProvider FormatProvider
            {
                get
                {
                    return this.formatProviderField ;
                }
                set
                {
                    if ((value != null))
                    {
                        this.formatProviderField  = value;
                    }
                }
            }
            /// <summary>
            /// This is called from the compile/run appdomain to convert objects within an expression block to a string
            /// </summary>
            public string ToStringWithCulture(object objectToConvert)
            {
                if ((objectToConvert == null))
                {
                    throw new global::System.ArgumentNullException("objectToConvert");
                }
                System.Type t = objectToConvert.GetType();
                System.Reflection.MethodInfo method = t.GetMethod("ToString", new System.Type[] {
                            typeof(System.IFormatProvider)});
                if ((method == null))
                {
                    return objectToConvert.ToString();
                }
                else
                {
                    return ((string)(method.Invoke(objectToConvert, new object[] {
                                this.formatProviderField })));
                }
            }
        }
        private ToStringInstanceHelper toStringHelperField = new ToStringInstanceHelper();
        /// <summary>
        /// Helper to produce culture-oriented representation of an object as a string
        /// </summary>
        public ToStringInstanceHelper ToStringHelper
        {
            get
            {
                return this.toStringHelperField;
            }
        }
        #endregion
    }
    #endregion
}
