// ------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Версия среды выполнения: 16.0.0.0
//  
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторного создания кода.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace TemplateHOG.templates
{
    using System.Linq;
    using System.Text;
    using System.Collections.Generic;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "D:\work\Projects\HOGFW\templates\mmg.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "16.0.0.0")]
    public partial class mmg : mmgBase
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public virtual string TransformText()
        {
            
            #line 7 "D:\work\Projects\HOGFW\templates\mmg.tt"

    rmname = deploy? "inv_complex_inv" : rmname;
    zoom = deploy? false : zoom;
    string prg_start = "";
    for (int i = 0; i < prg_start_arr.Length; i++)
    {
        prg_start = "\""+String.Join("\",\"",prg_start_arr)+"\"";
    }

    string objzone = "gfx_"+zzname+"_win_"+mmgname+"_zone";
    string objroot = "obj_"+zzname+"_win_"+mmgname+(zoom?"_zoom":"_nozoom");


            
            #line default
            #line hidden
            this.Write("zzname = ");
            
            #line 20 "D:\work\Projects\HOGFW\templates\mmg.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(zzname));
            
            #line default
            #line hidden
            this.Write("          | без zz_ |\r\nmmgname = ");
            
            #line 21 "D:\work\Projects\HOGFW\templates\mmg.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(mmgname));
            
            #line default
            #line hidden
            this.Write("        | без win_ обычно равно имени зз |\r\nrmname = ");
            
            #line 22 "D:\work\Projects\HOGFW\templates\mmg.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(rmname));
            
            #line default
            #line hidden
            this.Write("          | без rm_ |\r\nprg_start = ");
            
            #line 23 "D:\work\Projects\HOGFW\templates\mmg.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(prg_start));
            
            #line default
            #line hidden
            this.Write("        | с use_ clk_ |\r\ndeploy = ");
            
            #line 24 "D:\work\Projects\HOGFW\templates\mmg.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(deploy));
            
            #line default
            #line hidden
            this.Write("          | in Inventory item |\r\nzoom = ");
            
            #line 25 "D:\work\Projects\HOGFW\templates\mmg.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(zoom));
            
            #line default
            #line hidden
            this.Write("              | in zoomable additional back |\r\nswapper = ");
            
            #line 26 "D:\work\Projects\HOGFW\templates\mmg.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(swapper));
            
            #line default
            #line hidden
            this.Write("        | puzzle with swapable mechanics(select, deselect, swap) |\r\n\r\n");
            
            #line 28 "D:\work\Projects\HOGFW\templates\mmg.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(objzone));
            
            #line default
            #line hidden
            this.Write("      | zone |\r\n");
            
            #line 29 "D:\work\Projects\HOGFW\templates\mmg.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(objroot));
            
            #line default
            #line hidden
            this.Write("      | root |\r\n=================================================================" +
                    "================================================================================" +
                    "===========================\r\n=======xml==========\r\n\r\n");
            
            #line 33 "D:\work\Projects\HOGFW\templates\mmg.tt"
 if (zoom) {
            
            #line default
            #line hidden
            this.Write("                <obj __type=\"spr_gm\" _name=\"");
            
            #line 34 "D:\work\Projects\HOGFW\templates\mmg.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(objroot));
            
            #line default
            #line hidden
            this.Write("\" alp=\"0\" input=\"0\" pos_z=\"50\">\r\n                    <obj __type=\"obj\" _name=\"");
            
            #line 35 "D:\work\Projects\HOGFW\templates\mmg.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(objroot));
            
            #line default
            #line hidden
            this.Write("_block\" inputrect_h=\"200\" inputrect_init=\"1\" inputrect_w=\"200\" inputrect_x=\"-100\"" +
                    " inputrect_y=\"-100\" pos_z=\"60\">\r\n");
            
            #line 36 "D:\work\Projects\HOGFW\templates\mmg.tt"
}else{
            
            #line default
            #line hidden
            this.Write("                <obj __type=\"spr_gm\" _name=\"");
            
            #line 37 "D:\work\Projects\HOGFW\templates\mmg.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(objroot));
            
            #line default
            #line hidden
            this.Write("\" input=\"0\" pos_z=\"10\">\r\n");
            
            #line 38 "D:\work\Projects\HOGFW\templates\mmg.tt"
}
            
            #line default
            #line hidden
            
            #line 39 "D:\work\Projects\HOGFW\templates\mmg.tt"
    if (swapper) {
            
            #line default
            #line hidden
            this.Write("                        <obj __type=\"obj\" _name=\"obj_");
            
            #line 40 "D:\work\Projects\HOGFW\templates\mmg.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(zzname));
            
            #line default
            #line hidden
            this.Write("_field\">\r\n                            <obj __type=\"obj\" _name=\"obj_");
            
            #line 41 "D:\work\Projects\HOGFW\templates\mmg.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(zzname));
            
            #line default
            #line hidden
            this.Write("_piece_1\">\r\n                                <obj __type=\"spr\" _name=\"spr_");
            
            #line 42 "D:\work\Projects\HOGFW\templates\mmg.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(zzname));
            
            #line default
            #line hidden
            this.Write("_piece_1\" res=\"assets/back\">\r\n                                    <obj __type=\"sp" +
                    "r\" _name=\"spr_");
            
            #line 43 "D:\work\Projects\HOGFW\templates\mmg.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(zzname));
            
            #line default
            #line hidden
            this.Write("_piece_1_light\" alp=\"0\" ang=\"1.57\" blendmode=\"2\" input=\"0\" res=\"assets/back\"/>\r\n " +
                    "                               </obj>\r\n                            </obj>\r\n     " +
                    "                       <obj __type=\"obj\" _name=\"obj_");
            
            #line 46 "D:\work\Projects\HOGFW\templates\mmg.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(zzname));
            
            #line default
            #line hidden
            this.Write("_piece_2\">\r\n                                <obj __type=\"spr\" _name=\"spr_");
            
            #line 47 "D:\work\Projects\HOGFW\templates\mmg.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(zzname));
            
            #line default
            #line hidden
            this.Write("_piece_2\" res=\"assets/back\">\r\n                                    <obj __type=\"sp" +
                    "r\" _name=\"spr_");
            
            #line 48 "D:\work\Projects\HOGFW\templates\mmg.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(zzname));
            
            #line default
            #line hidden
            this.Write("_piece_2_light\" alp=\"0\" ang=\"1.57\" blendmode=\"2\" input=\"0\" res=\"assets/back\"/>\r\n " +
                    "                               </obj>\r\n                            </obj>\r\n     " +
                    "                   </obj>\r\n");
            
            #line 52 "D:\work\Projects\HOGFW\templates\mmg.tt"
}
            
            #line default
            #line hidden
            
            #line 53 "D:\work\Projects\HOGFW\templates\mmg.tt"
 if (zoom) {
            
            #line default
            #line hidden
            this.Write("                    </obj>\r\n                </obj>\r\n");
            
            #line 56 "D:\work\Projects\HOGFW\templates\mmg.tt"
}else{
            
            #line default
            #line hidden
            this.Write("                </obj>\r\n");
            
            #line 58 "D:\work\Projects\HOGFW\templates\mmg.tt"
}
            
            #line default
            #line hidden
            this.Write("\r\n=======lua==========\r\n\r\n==");
            
            #line 62 "D:\work\Projects\HOGFW\templates\mmg.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(prg_start));
            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 63 "D:\work\Projects\HOGFW\templates\mmg.tt"
 foreach (var progress in prg_start_arr) {
            
            #line default
            #line hidden
            this.Write("==");
            
            #line 64 "D:\work\Projects\HOGFW\templates\mmg.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(progress));
            
            #line default
            #line hidden
            this.Write("\r\n\r\nprivate.");
            
            #line 66 "D:\work\Projects\HOGFW\templates\mmg.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(progress));
            
            #line default
            #line hidden
            
            #line 66 "D:\work\Projects\HOGFW\templates\mmg.tt"
 Selector(zoom,"_logic","_end");
            
            #line default
            #line hidden
            this.Write(" = function()\r\n  if ld.CheckRequirements( {");
            
            #line 67 "D:\work\Projects\HOGFW\templates\mmg.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(prg_start));
            
            #line default
            #line hidden
            this.Write("} ) then\r\n");
            
            #line 68 "D:\work\Projects\HOGFW\templates\mmg.tt"
 if (zoom) {
            
            #line default
            #line hidden
            this.Write("    ObjSet( \"");
            
            #line 69 "D:\work\Projects\HOGFW\templates\mmg.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(objzone));
            
            #line default
            #line hidden
            this.Write("\", { visible = 1, input = 1, active = 1 } )\r\n    ld.mmgZoomInit(\"win_");
            
            #line 70 "D:\work\Projects\HOGFW\templates\mmg.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(mmgname));
            
            #line default
            #line hidden
            this.Write("\");\r\n");
            
            #line 71 "D:\work\Projects\HOGFW\templates\mmg.tt"
}else{
            
            #line default
            #line hidden
            this.Write("    ObjSet( \"");
            
            #line 72 "D:\work\Projects\HOGFW\templates\mmg.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(objroot));
            
            #line default
            #line hidden
            this.Write("\", {input = 1} );\r\n");
            
            #line 73 "D:\work\Projects\HOGFW\templates\mmg.tt"
}
            
            #line default
            #line hidden
            this.Write("  end\r\nend;\r\n\r\n==\r\n\r\n  local func_end = function()\r\n");
            
            #line 80 "D:\work\Projects\HOGFW\templates\mmg.tt"
 if (prg_start_arr.Length > 1) {
            
            #line default
            #line hidden
            this.Write("    if ld.CheckRequirements( {");
            
            #line 81 "D:\work\Projects\HOGFW\templates\mmg.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(prg_start));
            
            #line default
            #line hidden
            this.Write("} ) then\r\n");
            
            #line 82 "D:\work\Projects\HOGFW\templates\mmg.tt"
} 
            
            #line default
            #line hidden
            
            #line 83 "D:\work\Projects\HOGFW\templates\mmg.tt"
 if (zoom) {
            
            #line default
            #line hidden
            this.Write("    ld_impl.mmgZoomShow( \"win_");
            
            #line 84 "D:\work\Projects\HOGFW\templates\mmg.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(mmgname));
            
            #line default
            #line hidden
            this.Write("\" )\r\n");
            
            #line 85 "D:\work\Projects\HOGFW\templates\mmg.tt"
}else{
            
            #line default
            #line hidden
            this.Write("    private.win_");
            
            #line 86 "D:\work\Projects\HOGFW\templates\mmg.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(mmgname));
            
            #line default
            #line hidden
            this.Write("_init();\r\n");
            
            #line 87 "D:\work\Projects\HOGFW\templates\mmg.tt"
}
            
            #line default
            #line hidden
            
            #line 88 "D:\work\Projects\HOGFW\templates\mmg.tt"
 if (prg_start_arr.Length > 1) {
            
            #line default
            #line hidden
            this.Write("    end\r\n");
            
            #line 90 "D:\work\Projects\HOGFW\templates\mmg.tt"
} 
            
            #line default
            #line hidden
            this.Write("  end\r\n\r\n");
            
            #line 93 "D:\work\Projects\HOGFW\templates\mmg.tt"
 }//end foreach
            
            #line default
            #line hidden
            this.Write("==========\r\n\r\nprivate.win_");
            
            #line 96 "D:\work\Projects\HOGFW\templates\mmg.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(mmgname));
            
            #line default
            #line hidden
            this.Write("_logic = function()\r\n  if ld.CheckRequirements( {\"win_");
            
            #line 97 "D:\work\Projects\HOGFW\templates\mmg.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(mmgname));
            
            #line default
            #line hidden
            this.Write("\"} ) then\r\n  end\r\nend;\r\n\r\nprivate.win_");
            
            #line 101 "D:\work\Projects\HOGFW\templates\mmg.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(mmgname));
            
            #line default
            #line hidden
            this.Write("_beg = function(force)\r\n  if ld.CheckRequirements( {\"win_");
            
            #line 102 "D:\work\Projects\HOGFW\templates\mmg.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(mmgname));
            
            #line default
            #line hidden
            this.Write("\"} ) or force then\r\n    ObjDelete( \"");
            
            #line 103 "D:\work\Projects\HOGFW\templates\mmg.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(objzone));
            
            #line default
            #line hidden
            this.Write("\" );\r\n");
            
            #line 104 "D:\work\Projects\HOGFW\templates\mmg.tt"
    if (!zoom) {
            
            #line default
            #line hidden
            this.Write("    ObjSet(\"obj_");
            
            #line 105 "D:\work\Projects\HOGFW\templates\mmg.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(zzname));
            
            #line default
            #line hidden
            this.Write("_win_");
            
            #line 105 "D:\work\Projects\HOGFW\templates\mmg.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(mmgname));
            
            #line default
            #line hidden
            this.Write("_nozoom\",{input = 0});\r\n    --ObjDelete(\"obj_");
            
            #line 106 "D:\work\Projects\HOGFW\templates\mmg.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(zzname));
            
            #line default
            #line hidden
            this.Write("_win_");
            
            #line 106 "D:\work\Projects\HOGFW\templates\mmg.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(mmgname));
            
            #line default
            #line hidden
            this.Write("_nozoom\");\r\n");
            
            #line 107 "D:\work\Projects\HOGFW\templates\mmg.tt"
}
            
            #line default
            #line hidden
            this.Write("  end\r\nend;\r\n\r\nprivate.win_");
            
            #line 111 "D:\work\Projects\HOGFW\templates\mmg.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(mmgname));
            
            #line default
            #line hidden
            this.Write("_end = function()\r\n  if ld.CheckRequirements( {\"win_");
            
            #line 112 "D:\work\Projects\HOGFW\templates\mmg.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(mmgname));
            
            #line default
            #line hidden
            this.Write("\"} ) then\r\n");
            
            #line 113 "D:\work\Projects\HOGFW\templates\mmg.tt"
    if (!deploy) {
            
            #line default
            #line hidden
            this.Write("    ld.SubRoom.Complete( \"win_");
            
            #line 114 "D:\work\Projects\HOGFW\templates\mmg.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(mmgname));
            
            #line default
            #line hidden
            this.Write("\" )\r\n");
            
            #line 115 "D:\work\Projects\HOGFW\templates\mmg.tt"
}
            
            #line default
            #line hidden
            this.Write("  end  \r\nend;\r\n\r\n=V=========\r\nfunction public.win_");
            
            #line 120 "D:\work\Projects\HOGFW\templates\mmg.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(mmgname));
            
            #line default
            #line hidden
            this.Write("()\r\n\r\n  private.win_");
            
            #line 122 "D:\work\Projects\HOGFW\templates\mmg.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(mmgname));
            
            #line default
            #line hidden
            this.Write("_beg(true)\r\n");
            
            #line 123 "D:\work\Projects\HOGFW\templates\mmg.tt"
    if (zoom) {
            
            #line default
            #line hidden
            this.Write("  ld_impl.mmgZoomShow( \"win_");
            
            #line 124 "D:\work\Projects\HOGFW\templates\mmg.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(mmgname));
            
            #line default
            #line hidden
            this.Write("\" )\r\n");
            
            #line 125 "D:\work\Projects\HOGFW\templates\mmg.tt"
}else{
            
            #line default
            #line hidden
            this.Write("  cmn.MiniGameHide( \"");
            
            #line 126 "D:\work\Projects\HOGFW\templates\mmg.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(mmgname));
            
            #line default
            #line hidden
            this.Write("\", true );\r\n");
            
            #line 127 "D:\work\Projects\HOGFW\templates\mmg.tt"
}
            
            #line default
            #line hidden
            this.Write("\r\n=V=========\r\nfunction private.win_");
            
            #line 130 "D:\work\Projects\HOGFW\templates\mmg.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(mmgname));
            
            #line default
            #line hidden
            this.Write("_init()\r\n\r\n");
            
            #line 132 "D:\work\Projects\HOGFW\templates\mmg.tt"
    if (!zoom) {
            
            #line default
            #line hidden
            this.Write("  if ld.CheckRequirements( { ");
            
            #line 133 "D:\work\Projects\HOGFW\templates\mmg.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(prg_start));
            
            #line default
            #line hidden
            this.Write(" } ) and not ld.CheckRequirements( { \"win_");
            
            #line 133 "D:\work\Projects\HOGFW\templates\mmg.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(mmgname));
            
            #line default
            #line hidden
            this.Write("\" } ) then\r\n    cmn.MiniGameShow( \"");
            
            #line 134 "D:\work\Projects\HOGFW\templates\mmg.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(mmgname));
            
            #line default
            #line hidden
            this.Write("\" );\r\n  end\r\n");
            
            #line 136 "D:\work\Projects\HOGFW\templates\mmg.tt"
}
            
            #line default
            #line hidden
            this.Write("  \r\n  if private.win_");
            
            #line 137 "D:\work\Projects\HOGFW\templates\mmg.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(mmgname));
            
            #line default
            #line hidden
            this.Write("_gm then return end\r\n  private.win_");
            
            #line 138 "D:\work\Projects\HOGFW\templates\mmg.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(mmgname));
            
            #line default
            #line hidden
            this.Write("_gm = {}\r\n  local gm = private.win_");
            
            #line 139 "D:\work\Projects\HOGFW\templates\mmg.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(mmgname));
            
            #line default
            #line hidden
            this.Write(@"_gm;

--********************************************************************************************************************* 
--function gm.model() end
--*********************************************************************************************************************
  
  function gm.model_init()
");
            
            #line 146 "D:\work\Projects\HOGFW\templates\mmg.tt"
    if (swapper) {
            
            #line default
            #line hidden
            this.Write("    gm.model_pieces = 2 --num of pieces\r\n");
            
            #line 148 "D:\work\Projects\HOGFW\templates\mmg.tt"
}
            
            #line default
            #line hidden
            this.Write(@"    gm.model_load()
  end

  function gm.model_load()
    if gm.progress.state then
      gm.state = ld.TableCopy( gm.progress.state )
    else
      gm.model_reset()
    end
  end

  function gm.model_save()
    gm.progress.state = ld.TableCopy( gm.state )
  end

  function gm.model_reset()
    gm.model_prev_state = ld.Table.Copy(gm.state)
    gm.state = gm.model_get_state_default()
  end

  function gm.model_is_fake_reset()
    return (gm.model_prev_state and ld.Table.Equals(gm.model_prev_state,gm.state))
  end

  function gm.model_skip()
    gm.state = gm.model_get_state_win()
  end

  function gm.model_win_check()
");
            
            #line 178 "D:\work\Projects\HOGFW\templates\mmg.tt"
    if (swapper) {
            
            #line default
            #line hidden
            this.Write("    --change check if different conditions of win\r\n");
            
            #line 180 "D:\work\Projects\HOGFW\templates\mmg.tt"
}
            
            #line default
            #line hidden
            this.Write("  \r\n    return ld.Table.Equals( gm.state, gm.model_get_state_win() )\r\n  end\r\n\r\n  " +
                    "function gm.model_get_state_default()\r\n    if gm.state_default == nil then\r\n");
            
            #line 186 "D:\work\Projects\HOGFW\templates\mmg.tt"
    if (swapper) {
            
            #line default
            #line hidden
            this.Write("     gm.state_default = { 2, 1 }\r\n");
            
            #line 188 "D:\work\Projects\HOGFW\templates\mmg.tt"
}else{
            
            #line default
            #line hidden
            this.Write("     gm.state_default = { 0 }\r\n");
            
            #line 190 "D:\work\Projects\HOGFW\templates\mmg.tt"
}
            
            #line default
            #line hidden
            this.Write("    end\r\n    return ld.Table.Copy( gm.state_default )\r\n  end\r\n\r\n  function gm.mod" +
                    "el_get_state_win()\r\n    if gm.state_win == nil then\r\n");
            
            #line 197 "D:\work\Projects\HOGFW\templates\mmg.tt"
    if (swapper) {
            
            #line default
            #line hidden
            this.Write("     gm.state_win = { 1, 2 }\r\n");
            
            #line 199 "D:\work\Projects\HOGFW\templates\mmg.tt"
}else{
            
            #line default
            #line hidden
            this.Write("     gm.state_win = { 0 }\r\n");
            
            #line 201 "D:\work\Projects\HOGFW\templates\mmg.tt"
}
            
            #line default
            #line hidden
            this.Write("    end\r\n    return ld.Table.Copy( gm.state_win )\r\n  end\r\n\r\n");
            
            #line 206 "D:\work\Projects\HOGFW\templates\mmg.tt"
    if (swapper) {
            
            #line default
            #line hidden
            this.Write("  function gm.model_mdown(id1, id2)\r\n    gm.state[id1], gm.state[id2] = gm.state[" +
                    "id2], gm.state[id1]\r\n  end\r\n");
            
            #line 210 "D:\work\Projects\HOGFW\templates\mmg.tt"
}else{
            
            #line default
            #line hidden
            this.Write("  function gm.model_mdown(id)\r\n    gm.state[id] = gm.state[id] + 1\r\n  end     \r\n");
            
            #line 214 "D:\work\Projects\HOGFW\templates\mmg.tt"
}
            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 216 "D:\work\Projects\HOGFW\templates\mmg.tt"
    if (swapper) {
            
            #line default
            #line hidden
            this.Write("  function gm.model_is_correct_to_select(id1, id2)\r\n    --replace with correct co" +
                    "ndition if select condition exist\r\n    return true\r\n  end\r\n     \r\n");
            
            #line 222 "D:\work\Projects\HOGFW\templates\mmg.tt"
}
            
            #line default
            #line hidden
            this.Write(@"--*********************************************************************************************************************
--function gm.view() end
--*********************************************************************************************************************

  function gm.view_init()
");
            
            #line 228 "D:\work\Projects\HOGFW\templates\mmg.tt"
    if (swapper) {
            
            #line default
            #line hidden
            this.Write("    gm.view_obj = function(n) return string.format(\"obj_");
            
            #line 229 "D:\work\Projects\HOGFW\templates\mmg.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(mmgname));
            
            #line default
            #line hidden
            this.Write("_piece_%d\",n) end ;\r\n    gm.view_spr = function(n) return string.format(\"spr_");
            
            #line 230 "D:\work\Projects\HOGFW\templates\mmg.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(mmgname));
            
            #line default
            #line hidden
            this.Write("_piece_%d\",n) end ;\r\n    gm.view_light = function(n) return string.format(\"spr_");
            
            #line 231 "D:\work\Projects\HOGFW\templates\mmg.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(mmgname));
            
            #line default
            #line hidden
            this.Write("_piece_%d_light\",n) end ;\r\n");
            
            #line 232 "D:\work\Projects\HOGFW\templates\mmg.tt"
}
            
            #line default
            #line hidden
            this.Write("    gm.view_skip_reset_time = 0.5\r\n    gm.view_fake_reset_time = 1\r\n    gm.view_a" +
                    "nimtime = 0.5\r\n    gm.view_build()\r\n    gm.view_update_all()\r\n  end\r\n\r\n  functio" +
                    "n gm.view_build()\r\n");
            
            #line 241 "D:\work\Projects\HOGFW\templates\mmg.tt"
    if (swapper) {
            
            #line default
            #line hidden
            this.Write(@"    for i,o in ipairs(gm.state) do
      ObjSet( gm.view_spr(i), {
        event_mdown = function() gm.controller_event_mdown( i ) end;
        event_menter = function() gm.controller_event_menter( i ) end;
        event_mleave = function() gm.controller_event_mleave( i ) end;
      } );
    end
");
            
            #line 249 "D:\work\Projects\HOGFW\templates\mmg.tt"
}
            
            #line default
            #line hidden
            this.Write("  end\r\n\r\n");
            
            #line 252 "D:\work\Projects\HOGFW\templates\mmg.tt"
    if (swapper) {
            
            #line default
            #line hidden
            this.Write(@"  function gm.view_set( id, time, func_end )
    local val = gm.state[id]
    ld.Anim.Set(gm.view_obj(id), {pos_x = val*100}, time)
    if time then
      local scale_percent_time = 0.1
      local scale_max = 1.05 
      ld.Anim.Set(gm.view_obj(id), {scale_x = scale_max, scale_y = scale_max}, time*scale_percent_time)
      ld.StartTimer( time*(1-scale_percent_time), function()  
        ld.Anim.Set(gm.view_obj(id), {scale_x = 1, scale_y = 1}, time*scale_percent_time)
      end )
    end
    if func_end then
      ld.StartTimer( time, func_end )
    end
  end 

");
            
            #line 269 "D:\work\Projects\HOGFW\templates\mmg.tt"
}
            
            #line default
            #line hidden
            this.Write(@"  function gm.view_get_obj_menter_name( id )
    return gm.view_light( id )
  end

  function gm.view_win( func_end )    
    if func_end then
      func_end()
    else
      
    end
  end

  function gm.view_reset( func_end )
    if gm.model_is_fake_reset() then  --fake reset(nothing changed from begining of game)
");
            
            #line 284 "D:\work\Projects\HOGFW\templates\mmg.tt"
    if (swapper) {
            
            #line default
            #line hidden
            this.Write(@"      local atl = ld.Anim.Liquid( gm.view_fake_reset_time, gm.model_pieces, 0, 1   , 0.9 )
      local ats = ld.Anim.Liquid( gm.view_fake_reset_time, gm.model_pieces, 1, 1.05, 0.9 )
      for i,o in ipairs(gm.state) do
        ObjAnimate( gm.view_light(i), 8, 0, 0, function() end, atl[ o ] );
        ObjAnimate( gm.view_obj(i), ""scale_x"", 0, 0, function() end, ats[ o ] );
        ObjAnimate( gm.view_obj(i), ""scale_y"", 0, 0, function() end, ats[ o ] );
      end
      ld.StartTimer( gm.view_fake_reset_time, func_end )
");
            
            #line 293 "D:\work\Projects\HOGFW\templates\mmg.tt"
}else{
            
            #line default
            #line hidden
            this.Write("      --replace with custom fake reset\r\n      gm.view_update_all( func_end, gm.vi" +
                    "ew_fake_reset_time )  \r\n");
            
            #line 296 "D:\work\Projects\HOGFW\templates\mmg.tt"
}
            
            #line default
            #line hidden
            this.Write("    else\r\n      gm.view_update_all( func_end, gm.view_skip_reset_time )\r\n    end\r" +
                    "\n  end\r\n\r\n  function gm.view_update_all( func_end, time )\r\n    for i,o in ipairs" +
                    "(gm.state) do\r\n");
            
            #line 304 "D:\work\Projects\HOGFW\templates\mmg.tt"
    if (swapper) {
            
            #line default
            #line hidden
            this.Write("      if gm.model_prev_state and gm.model_prev_state[i] == o then --already on th" +
                    "at point\r\n      else\r\n        gm.view_set( i, time )\r\n      end     \r\n");
            
            #line 309 "D:\work\Projects\HOGFW\templates\mmg.tt"
}
            
            #line default
            #line hidden
            this.Write("    end\r\n    if func_end then \r\n      ld.StartTimer( time, func_end )\r\n    end\r\n " +
                    " end\r\n\r\n  function gm.view_menter( id )\r\n    local obj = gm.view_get_obj_menter_" +
                    "name( id )\r\n    ld.Anim.Light( obj, true )\r\n  end\r\n\r\n  function gm.view_mleave( " +
                    "id");
            
            #line 321 "D:\work\Projects\HOGFW\templates\mmg.tt"
    if (swapper) {
            
            #line default
            #line hidden
            this.Write(", force");
            
            #line 321 "D:\work\Projects\HOGFW\templates\mmg.tt"
}
            
            #line default
            #line hidden
            this.Write(" )\r\n    local obj = gm.view_get_obj_menter_name( id )\r\n");
            
            #line 323 "D:\work\Projects\HOGFW\templates\mmg.tt"
    if (swapper) {
            
            #line default
            #line hidden
            this.Write("    if id ~= gm.controller_selected or force then\r\n      ld.Anim.Light( obj, fals" +
                    "e )\r\n    end\r\n");
            
            #line 327 "D:\work\Projects\HOGFW\templates\mmg.tt"
}else{
            
            #line default
            #line hidden
            this.Write("    ld.Anim.Light( obj, false )\r\n");
            
            #line 329 "D:\work\Projects\HOGFW\templates\mmg.tt"
}
            
            #line default
            #line hidden
            this.Write("  end\r\n\r\n");
            
            #line 332 "D:\work\Projects\HOGFW\templates\mmg.tt"
    if (swapper) {
            
            #line default
            #line hidden
            this.Write(@"  function gm.view_mdown( id1, id2, func_end )
    --gm.view_select(id1, 1) --if needed
    --gm.view_select(id2, 1) --if needed
    gm.view_set(id1, gm.view_animtime, function()  
      --gm.view_select(id1, 0) --if needed
      --gm.view_select(id2, 0) --if needed
      func_end()
    end)
    gm.view_set(id2, gm.view_animtime)
  end

  function gm.view_select(id, val)
    --val == 1 make select, val == 0 deselect
    ObjSet( gm.view_obj(id), {pos_z = val} );
  end
");
            
            #line 348 "D:\work\Projects\HOGFW\templates\mmg.tt"
}else{
            
            #line default
            #line hidden
            this.Write("  function gm.view_mdown( id, func_end )\r\n    ld.StartTimer( 0.5, function() func" +
                    "_end() end )\r\n  end     \r\n");
            
            #line 352 "D:\work\Projects\HOGFW\templates\mmg.tt"
}
            
            #line default
            #line hidden
            this.Write(@"
--*********************************************************************************************************************
--function gm.controller() end
--*********************************************************************************************************************

  function gm.controller_init()
    if not gm.controller_initialized then
      private.cur_prg = ng_global.currentprogress; 
      gm.progress = ng_global.progress[ private.cur_prg ][ ""win_");
            
            #line 361 "D:\work\Projects\HOGFW\templates\mmg.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(mmgname));
            
            #line default
            #line hidden
            this.Write("\" ]\r\n      gm.model_init()\r\n      gm.view_init()\r\n      gm.controller_initialized" +
                    " = true;\r\n    end;\r\n  end\r\n\r\n  function gm.controller_save()\r\n    gm.model_save(" +
                    ")\r\n  end\r\n\r\n  function gm.controller_skip()\r\n    if ld.Lock( 1 ) then\r\n");
            
            #line 374 "D:\work\Projects\HOGFW\templates\mmg.tt"
    if (swapper) {
            
            #line default
            #line hidden
            this.Write("      if gm.controller_selected then\r\n        gm.view_select( gm.controller_selec" +
                    "ted, 0 )\r\n        gm.view_mleave( gm.controller_selected, 1 )\r\n        gm.contro" +
                    "ller_selected = nil\r\n      end     \r\n");
            
            #line 380 "D:\work\Projects\HOGFW\templates\mmg.tt"
}
            
            #line default
            #line hidden
            this.Write("      gm.model_skip()\r\n      gm.view_reset( gm.controller_event_end )\r\n    end\r\n " +
                    " end\r\n\r\n  function gm.controller_reset()\r\n    if ld.Lock( 1 ) then\r\n");
            
            #line 388 "D:\work\Projects\HOGFW\templates\mmg.tt"
    if (swapper) {
            
            #line default
            #line hidden
            this.Write("      if gm.controller_selected then\r\n        gm.view_select( gm.controller_selec" +
                    "ted, 0 )\r\n        gm.view_mleave( gm.controller_selected, 1 )\r\n        gm.contro" +
                    "ller_selected = nil\r\n      end     \r\n");
            
            #line 394 "D:\work\Projects\HOGFW\templates\mmg.tt"
}
            
            #line default
            #line hidden
            this.Write("      gm.model_reset()\r\n      gm.view_reset( gm.controller_event_end )\r\n    end\r\n" +
                    "  end\r\n\r\n  function gm.controller_win()\r\n    gm.view_win( public.win_");
            
            #line 401 "D:\work\Projects\HOGFW\templates\mmg.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(mmgname));
            
            #line default
            #line hidden
            this.Write(@" )
  end

  function gm.controller_event_end()
    if gm.model_win_check() then
      gm.controller_win()
    else
      gm.controller_save()
      ld.Lock( 0 )
    end
  end

  function gm.controller_event_menter( id )
    ld.ShCur(CURSOR_HAND)
    gm.view_menter( id )
  end

  function gm.controller_event_mleave( id )
    ld.ShCur(CURSOR_DEFAULT)
    gm.view_mleave( id )
  end

  function gm.controller_event_mdown( id )
");
            
            #line 424 "D:\work\Projects\HOGFW\templates\mmg.tt"
    if (swapper) {
            
            #line default
            #line hidden
            this.Write(@"    if gm.controller_selected == nil then --new selection
      gm.controller_selected = id
      gm.view_select( id, 1 )
    else
      if gm.controller_selected == id then --deselect
        gm.controller_selected = nil
        gm.view_select( id, 0 )
      else
        if gm.model_is_correct_to_select( gm.controller_selected, id ) then --swap
          if ld.Lock( 1 ) then
            gm.model_mdown( gm.controller_selected, id )
            gm.view_select( gm.controller_selected, 0 )
            gm.view_mleave( gm.controller_selected, 1 )
            gm.view_mdown( gm.controller_selected, id, gm.controller_event_end )
            gm.controller_selected = nil
          end
        else --select new
          gm.view_select( gm.controller_selected, 0 )
          gm.view_mleave( gm.controller_selected, 1 )
          gm.controller_selected = id
          gm.view_select( id, 1 )
        end
      end
    end     
");
            
            #line 449 "D:\work\Projects\HOGFW\templates\mmg.tt"
}else{
            
            #line default
            #line hidden
            this.Write("    if ld.Lock( 1 ) then\r\n      gm.model_mdown( id )\r\n      gm.view_mdown( id, gm" +
                    ".controller_event_end )\r\n    end     \r\n");
            
            #line 454 "D:\work\Projects\HOGFW\templates\mmg.tt"
}
            
            #line default
            #line hidden
            this.Write(@"  end

  function gm.controller_event_startdrag( id )

  end

  function gm.controller_event_drag( id )

  end

  function gm.controller_event_dragdrop( id )

  end

  gm.controller_init()    

end


=V========= 

function private.ResetSkip(command)
");
            
            #line 477 "D:\work\Projects\HOGFW\templates\mmg.tt"
    if (deploy) {
            
            #line default
            #line hidden
            this.Write("  local mg_name = interface.GetCurrentComplexInv()\r\n  local mg_name_formated = \"w" +
                    "in_\"..ld.StringDivide(mg_name)[3]..\"_gm\"\r\n");
            
            #line 480 "D:\work\Projects\HOGFW\templates\mmg.tt"
}else{
            
            #line default
            #line hidden
            this.Write("  local mg_name = common.GetCurrentSubRoom() or GetCurrentRoom();\r\n  local mg_nam" +
                    "e_formated = \"win_\"..ld.StringDivide(mg_name)[2]..\"_gm\"\r\n");
            
            #line 483 "D:\work\Projects\HOGFW\templates\mmg.tt"
}
            
            #line default
            #line hidden
            this.Write(@"  local call = private[mg_name_formated] and private[mg_name_formated][""controller_""..command] 
  if call and not ld.CheckRequirements( { ""win_""..ld.StringDivide(mg_name)[2] } ) then
    call()
  end
end

function public.Reset()
  private.ResetSkip(""reset"")
end;
function public.Skip()
  private.ResetSkip(""skip"")
end;

=V=========

");
            
            #line 499 "D:\work\Projects\HOGFW\templates\mmg.tt"
    if (deploy) {
            
            #line default
            #line hidden
            this.Write("public.");
            
            #line 500 "D:\work\Projects\HOGFW\templates\mmg.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(zzname));
            
            #line default
            #line hidden
            this.Write("_preopen = function()\r\n  private.win_");
            
            #line 501 "D:\work\Projects\HOGFW\templates\mmg.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(mmgname));
            
            #line default
            #line hidden
            this.Write("_init()\r\nend\r\n");
            
            #line 503 "D:\work\Projects\HOGFW\templates\mmg.tt"
}else{
            
            #line default
            #line hidden
            this.Write("  function zz_");
            
            #line 504 "D:\work\Projects\HOGFW\templates\mmg.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(zzname));
            
            #line default
            #line hidden
            this.Write(".PreOpen()\r\n    private.win_");
            
            #line 505 "D:\work\Projects\HOGFW\templates\mmg.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(mmgname));
            
            #line default
            #line hidden
            this.Write("_init()\r\n  end;\r\n");
            
            #line 507 "D:\work\Projects\HOGFW\templates\mmg.tt"
}
            
            #line default
            #line hidden
            this.Write("\r\n\r\n");
            return this.GenerationEnvironment.ToString();
        }
        
        #line 1 "D:\work\Projects\HOGFW\templates\t4helper.tt"

    void NeedComment(string message, bool comments)
    {
        Selector(comments,message,"");
        
        #line default
        #line hidden
        
        #line 5 "D:\work\Projects\HOGFW\templates\t4helper.tt"
}
    void Selector(bool selector, string messageTrue, string messageFalse)
    {
        string message = selector?messageTrue:messageFalse;
		if (message != "") {

        
        #line default
        #line hidden
        
        #line 10 "D:\work\Projects\HOGFW\templates\t4helper.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(message));

        
        #line default
        #line hidden
        
        #line 10 "D:\work\Projects\HOGFW\templates\t4helper.tt"

	}
}
        
        #line default
        #line hidden
    }
    
    #line default
    #line hidden
    #region Base class
    /// <summary>
    /// Base class for this transformation
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "16.0.0.0")]
    public class mmgBase
    {
        #region Fields
        private global::System.Text.StringBuilder generationEnvironmentField;
        private global::System.CodeDom.Compiler.CompilerErrorCollection errorsField;
        private global::System.Collections.Generic.List<int> indentLengthsField;
        private string currentIndentField = "";
        private bool endsWithNewline;
        private global::System.Collections.Generic.IDictionary<string, object> sessionField;
        #endregion
        #region Properties
        /// <summary>
        /// The string builder that generation-time code is using to assemble generated output
        /// </summary>
        protected System.Text.StringBuilder GenerationEnvironment
        {
            get
            {
                if ((this.generationEnvironmentField == null))
                {
                    this.generationEnvironmentField = new global::System.Text.StringBuilder();
                }
                return this.generationEnvironmentField;
            }
            set
            {
                this.generationEnvironmentField = value;
            }
        }
        /// <summary>
        /// The error collection for the generation process
        /// </summary>
        public System.CodeDom.Compiler.CompilerErrorCollection Errors
        {
            get
            {
                if ((this.errorsField == null))
                {
                    this.errorsField = new global::System.CodeDom.Compiler.CompilerErrorCollection();
                }
                return this.errorsField;
            }
        }
        /// <summary>
        /// A list of the lengths of each indent that was added with PushIndent
        /// </summary>
        private System.Collections.Generic.List<int> indentLengths
        {
            get
            {
                if ((this.indentLengthsField == null))
                {
                    this.indentLengthsField = new global::System.Collections.Generic.List<int>();
                }
                return this.indentLengthsField;
            }
        }
        /// <summary>
        /// Gets the current indent we use when adding lines to the output
        /// </summary>
        public string CurrentIndent
        {
            get
            {
                return this.currentIndentField;
            }
        }
        /// <summary>
        /// Current transformation session
        /// </summary>
        public virtual global::System.Collections.Generic.IDictionary<string, object> Session
        {
            get
            {
                return this.sessionField;
            }
            set
            {
                this.sessionField = value;
            }
        }
        #endregion
        #region Transform-time helpers
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void Write(string textToAppend)
        {
            if (string.IsNullOrEmpty(textToAppend))
            {
                return;
            }
            // If we're starting off, or if the previous text ended with a newline,
            // we have to append the current indent first.
            if (((this.GenerationEnvironment.Length == 0) 
                        || this.endsWithNewline))
            {
                this.GenerationEnvironment.Append(this.currentIndentField);
                this.endsWithNewline = false;
            }
            // Check if the current text ends with a newline
            if (textToAppend.EndsWith(global::System.Environment.NewLine, global::System.StringComparison.CurrentCulture))
            {
                this.endsWithNewline = true;
            }
            // This is an optimization. If the current indent is "", then we don't have to do any
            // of the more complex stuff further down.
            if ((this.currentIndentField.Length == 0))
            {
                this.GenerationEnvironment.Append(textToAppend);
                return;
            }
            // Everywhere there is a newline in the text, add an indent after it
            textToAppend = textToAppend.Replace(global::System.Environment.NewLine, (global::System.Environment.NewLine + this.currentIndentField));
            // If the text ends with a newline, then we should strip off the indent added at the very end
            // because the appropriate indent will be added when the next time Write() is called
            if (this.endsWithNewline)
            {
                this.GenerationEnvironment.Append(textToAppend, 0, (textToAppend.Length - this.currentIndentField.Length));
            }
            else
            {
                this.GenerationEnvironment.Append(textToAppend);
            }
        }
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void WriteLine(string textToAppend)
        {
            this.Write(textToAppend);
            this.GenerationEnvironment.AppendLine();
            this.endsWithNewline = true;
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void Write(string format, params object[] args)
        {
            this.Write(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void WriteLine(string format, params object[] args)
        {
            this.WriteLine(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Raise an error
        /// </summary>
        public void Error(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Raise a warning
        /// </summary>
        public void Warning(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            error.IsWarning = true;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Increase the indent
        /// </summary>
        public void PushIndent(string indent)
        {
            if ((indent == null))
            {
                throw new global::System.ArgumentNullException("indent");
            }
            this.currentIndentField = (this.currentIndentField + indent);
            this.indentLengths.Add(indent.Length);
        }
        /// <summary>
        /// Remove the last indent that was added with PushIndent
        /// </summary>
        public string PopIndent()
        {
            string returnValue = "";
            if ((this.indentLengths.Count > 0))
            {
                int indentLength = this.indentLengths[(this.indentLengths.Count - 1)];
                this.indentLengths.RemoveAt((this.indentLengths.Count - 1));
                if ((indentLength > 0))
                {
                    returnValue = this.currentIndentField.Substring((this.currentIndentField.Length - indentLength));
                    this.currentIndentField = this.currentIndentField.Remove((this.currentIndentField.Length - indentLength));
                }
            }
            return returnValue;
        }
        /// <summary>
        /// Remove any indentation
        /// </summary>
        public void ClearIndent()
        {
            this.indentLengths.Clear();
            this.currentIndentField = "";
        }
        #endregion
        #region ToString Helpers
        /// <summary>
        /// Utility class to produce culture-oriented representation of an object as a string.
        /// </summary>
        public class ToStringInstanceHelper
        {
            private System.IFormatProvider formatProviderField  = global::System.Globalization.CultureInfo.InvariantCulture;
            /// <summary>
            /// Gets or sets format provider to be used by ToStringWithCulture method.
            /// </summary>
            public System.IFormatProvider FormatProvider
            {
                get
                {
                    return this.formatProviderField ;
                }
                set
                {
                    if ((value != null))
                    {
                        this.formatProviderField  = value;
                    }
                }
            }
            /// <summary>
            /// This is called from the compile/run appdomain to convert objects within an expression block to a string
            /// </summary>
            public string ToStringWithCulture(object objectToConvert)
            {
                if ((objectToConvert == null))
                {
                    throw new global::System.ArgumentNullException("objectToConvert");
                }
                System.Type t = objectToConvert.GetType();
                System.Reflection.MethodInfo method = t.GetMethod("ToString", new System.Type[] {
                            typeof(System.IFormatProvider)});
                if ((method == null))
                {
                    return objectToConvert.ToString();
                }
                else
                {
                    return ((string)(method.Invoke(objectToConvert, new object[] {
                                this.formatProviderField })));
                }
            }
        }
        private ToStringInstanceHelper toStringHelperField = new ToStringInstanceHelper();
        /// <summary>
        /// Helper to produce culture-oriented representation of an object as a string
        /// </summary>
        public ToStringInstanceHelper ToStringHelper
        {
            get
            {
                return this.toStringHelperField;
            }
        }
        #endregion
    }
    #endregion
}
