// ------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Версия среды выполнения: 16.0.0.0
//  
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторного создания кода.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace TemplateHOG.templates
{
    using System.Linq;
    using System.Text;
    using System.Collections.Generic;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "D:\work\Projects\HOGFW\templates\dlg.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "16.0.0.0")]
    public partial class dlg : dlgBase
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public virtual string TransformText()
        {
            
            #line 7 "D:\work\Projects\HOGFW\templates\dlg.tt"

int val = 3;
if (count<2 || count >10) {
	if (item == "")
		count = 2;
	else
		count = 3;
	}
	prg = prg=="std"?"":prg;

            
            #line default
            #line hidden
            this.Write("rmname = ");
            
            #line 17 "D:\work\Projects\HOGFW\templates\dlg.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(rmname));
            
            #line default
            #line hidden
            this.Write("\t        | без rm_ |\r\ndlgname = ");
            
            #line 18 "D:\work\Projects\HOGFW\templates\dlg.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(dlgname));
            
            #line default
            #line hidden
            this.Write("\t    | без dlg_ |\r\n\r\nitem = ");
            
            #line 20 "D:\work\Projects\HOGFW\templates\dlg.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item==""?"-none-":item));
            
            #line default
            #line hidden
            this.Write("\t\t| подбираемый предмет |\r\nitemfuncget = ");
            
            #line 21 "D:\work\Projects\HOGFW\templates\dlg.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item==""?"-none-":itemfuncget));
            
            #line default
            #line hidden
            this.Write("\t    | ф-я давания |\r\nitemfunchand = ");
            
            #line 22 "D:\work\Projects\HOGFW\templates\dlg.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item==""?"-none-":itemfunchand));
            
            #line default
            #line hidden
            this.Write("    | ф-я статики руки |\r\ncount = ");
            
            #line 23 "D:\work\Projects\HOGFW\templates\dlg.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(count));
            
            #line default
            #line hidden
            this.Write("\t\t| счетчик диалогов |\r\nprg = ");
            
            #line 24 "D:\work\Projects\HOGFW\templates\dlg.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(prg));
            
            #line default
            #line hidden
            this.Write(@"        | текущий прогресс |
============================================================================================================================================================================
=======xml==========вне комнаты!!! Уже должно быть из шаблона

--            <obj __type=""spr_gm"" _name=""dlg_");
            
            #line 28 "D:\work\Projects\HOGFW\templates\dlg.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(rmname));
            
            #line default
            #line hidden
            this.Write("_");
            
            #line 28 "D:\work\Projects\HOGFW\templates\dlg.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(dlgname));
            
            #line default
            #line hidden
            this.Write("\" alp=\"0\" pos_x=\"512\" pos_y=\"384\" pos_z=\"111\">\r\n--                <obj __type=\"an" +
                    "im\" _name=\"anm_");
            
            #line 29 "D:\work\Projects\HOGFW\templates\dlg.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(rmname));
            
            #line default
            #line hidden
            this.Write("_");
            
            #line 29 "D:\work\Projects\HOGFW\templates\dlg.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(dlgname));
            
            #line default
            #line hidden
            this.Write("\" animfunc=\"static\" playing=\"1\" pos_x=\"-683\" pos_y=\"-384\" pos_z=\"999\" res=\"");
            
            #line 29 "D:\work\Projects\HOGFW\templates\dlg.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(path));
            
            #line default
            #line hidden
            this.Write("\">\r\n--                    <obj __type=\"obj\" _name=\"dlg_");
            
            #line 30 "D:\work\Projects\HOGFW\templates\dlg.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(rmname));
            
            #line default
            #line hidden
            this.Write("_");
            
            #line 30 "D:\work\Projects\HOGFW\templates\dlg.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(dlgname));
            
            #line default
            #line hidden
            this.Write("_lipsing_root\" anim_tag=\"head\" input=\"0\"/>\r\n--\t\t\t\t\t  <obj __type=\"anim\" _name=\"an" +
                    "m_");
            
            #line 31 "D:\work\Projects\HOGFW\templates\dlg.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(rmname));
            
            #line default
            #line hidden
            this.Write("_");
            
            #line 31 "D:\work\Projects\HOGFW\templates\dlg.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(dlgname));
            
            #line default
            #line hidden
            this.Write("_hand\" anim_tag=\"hand\" animfunc=\"");
            
            #line 31 "D:\work\Projects\HOGFW\templates\dlg.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(itemfuncget));
            
            #line default
            #line hidden
            this.Write("\" endtrig=\"0\" res=\"");
            
            #line 31 "D:\work\Projects\HOGFW\templates\dlg.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(path));
            
            #line default
            #line hidden
            this.Write("\">\r\n--                      <obj __type=\"anim\" _name=\"anm_");
            
            #line 32 "D:\work\Projects\HOGFW\templates\dlg.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(rmname));
            
            #line default
            #line hidden
            this.Write("_");
            
            #line 32 "D:\work\Projects\HOGFW\templates\dlg.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(dlgname));
            
            #line default
            #line hidden
            this.Write("_hand_static\" anim_tag=\"hand_static\" animfunc=\"");
            
            #line 32 "D:\work\Projects\HOGFW\templates\dlg.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(itemfunchand));
            
            #line default
            #line hidden
            this.Write("\" endtrig=\"0\" playing=\"1\" res=\"");
            
            #line 32 "D:\work\Projects\HOGFW\templates\dlg.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(path));
            
            #line default
            #line hidden
            this.Write("\"/>\r\n--                      <obj __type=\"obj\" _name=\"obj_");
            
            #line 33 "D:\work\Projects\HOGFW\templates\dlg.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(rmname));
            
            #line default
            #line hidden
            this.Write("_");
            
            #line 33 "D:\work\Projects\HOGFW\templates\dlg.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(dlgname));
            
            #line default
            #line hidden
            this.Write("_item\" anim_tag=\"item\" input=\"0\"/>\r\n--                      <obj __type=\"obj\" _na" +
                    "me=\"obj_");
            
            #line 34 "D:\work\Projects\HOGFW\templates\dlg.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(rmname));
            
            #line default
            #line hidden
            this.Write("_");
            
            #line 34 "D:\work\Projects\HOGFW\templates\dlg.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(dlgname));
            
            #line default
            #line hidden
            this.Write("_item_shadow\" anim_tag=\"item_shadow\" input=\"0\"/>\r\n--                    </obj>\r\n-" +
                    "-                </obj>\r\n--            </obj>\r\n            \r\n=======lua=========" +
                    "=\r\n\r\n==========\r\n\r\nfunction public.SwitchFrase( dlg_name, count_txt )\r\n  if dlg_" +
                    "name == \"");
            
            #line 44 "D:\work\Projects\HOGFW\templates\dlg.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(dlgname));
            
            #line default
            #line hidden
            this.Write("\" then\r\n    if count_txt == 1 then\r\n      common_impl.continue_visible = true\r\n  " +
                    "  elseif count_txt == 2 then\r\n      common_impl.continue_visible = true\r\n");
            
            #line 49 "D:\work\Projects\HOGFW\templates\dlg.tt"
 if (item != "" && item != null) {
            
            #line default
            #line hidden
            this.Write("      public.get_");
            
            #line 50 "D:\work\Projects\HOGFW\templates\dlg.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item));
            
            #line default
            #line hidden
            this.Write("_prepare()\r\n      ld.AnimPlay( \"anm_");
            
            #line 51 "D:\work\Projects\HOGFW\templates\dlg.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(rmname));
            
            #line default
            #line hidden
            this.Write("_");
            
            #line 51 "D:\work\Projects\HOGFW\templates\dlg.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(dlgname));
            
            #line default
            #line hidden
            this.Write("_hand\", \"");
            
            #line 51 "D:\work\Projects\HOGFW\templates\dlg.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(itemfuncget));
            
            #line default
            #line hidden
            this.Write("\", \"\" )\r\n    elseif count_txt == 3 then \r\n      private.dlg_");
            
            #line 53 "D:\work\Projects\HOGFW\templates\dlg.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(dlgname));
            
            #line default
            #line hidden
            this.Write("_");
            
            #line 53 "D:\work\Projects\HOGFW\templates\dlg.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item));
            
            #line default
            #line hidden
            this.Write("_collected = true\r\n      ld.Anim.Reverse(\"anm_");
            
            #line 54 "D:\work\Projects\HOGFW\templates\dlg.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(rmname));
            
            #line default
            #line hidden
            this.Write("_");
            
            #line 54 "D:\work\Projects\HOGFW\templates\dlg.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(dlgname));
            
            #line default
            #line hidden
            this.Write("_hand\")\r\n      cmn.CallEventHandler( \"get_");
            
            #line 55 "D:\work\Projects\HOGFW\templates\dlg.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item));
            
            #line default
            #line hidden
            this.Write("\" );\r\n");
            
            #line 56 "D:\work\Projects\HOGFW\templates\dlg.tt"
 val = 4;}
            
            #line default
            #line hidden
            
            #line 57 "D:\work\Projects\HOGFW\templates\dlg.tt"
 for (int i = val; i <= count; i++)
{
            
            #line default
            #line hidden
            this.Write("\telseif count_txt == ");
            
            #line 59 "D:\work\Projects\HOGFW\templates\dlg.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(i));
            
            #line default
            #line hidden
            this.Write(" then\r\n");
            
            #line 60 "D:\work\Projects\HOGFW\templates\dlg.tt"
} 
            
            #line default
            #line hidden
            this.Write("    end\r\n  end\r\nend\r\n\r\n\r\n=========================\r\n\r\nfunction public.dlg_");
            
            #line 68 "D:\work\Projects\HOGFW\templates\dlg.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(rmname));
            
            #line default
            #line hidden
            this.Write("_");
            
            #line 68 "D:\work\Projects\HOGFW\templates\dlg.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(dlgname));
            
            #line default
            #line hidden
            this.Write("( obj )\r\n  local func_end = function()\r\n");
            
            #line 70 "D:\work\Projects\HOGFW\templates\dlg.tt"
 if (item != "" && item != null) {
            
            #line default
            #line hidden
            this.Write("    cmn.SetEventDone( \"get_");
            
            #line 71 "D:\work\Projects\HOGFW\templates\dlg.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item));
            
            #line default
            #line hidden
            this.Write("\" );\r\n");
            
            #line 72 "D:\work\Projects\HOGFW\templates\dlg.tt"
}
            
            #line default
            #line hidden
            this.Write("    cmn.SetEventDone( \"dlg_");
            
            #line 73 "D:\work\Projects\HOGFW\templates\dlg.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(rmname));
            
            #line default
            #line hidden
            this.Write("_");
            
            #line 73 "D:\work\Projects\HOGFW\templates\dlg.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(dlgname));
            
            #line default
            #line hidden
            this.Write("\" );\r\n    cmn.CallEventHandler( \"dlg_");
            
            #line 74 "D:\work\Projects\HOGFW\templates\dlg.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(rmname));
            
            #line default
            #line hidden
            this.Write("_");
            
            #line 74 "D:\work\Projects\HOGFW\templates\dlg.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(dlgname));
            
            #line default
            #line hidden
            this.Write("_end\" );\r\n    common_impl.Lock(0);\r\n    ld.ShowBbtAfter( \"dlg_");
            
            #line 76 "D:\work\Projects\HOGFW\templates\dlg.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(rmname));
            
            #line default
            #line hidden
            this.Write("_");
            
            #line 76 "D:\work\Projects\HOGFW\templates\dlg.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(dlgname));
            
            #line default
            #line hidden
            this.Write("\" );\r\n  end;\r\n  function public.dlg_");
            
            #line 78 "D:\work\Projects\HOGFW\templates\dlg.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(rmname));
            
            #line default
            #line hidden
            this.Write("_");
            
            #line 78 "D:\work\Projects\HOGFW\templates\dlg.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(dlgname));
            
            #line default
            #line hidden
            this.Write("_func_end()\r\n    common_impl.Lock(1);\r\n");
            
            #line 80 "D:\work\Projects\HOGFW\templates\dlg.tt"
 if (item != "" && item != null) {
            
            #line default
            #line hidden
            this.Write("    if not private.dlg_");
            
            #line 81 "D:\work\Projects\HOGFW\templates\dlg.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(dlgname));
            
            #line default
            #line hidden
            this.Write("_");
            
            #line 81 "D:\work\Projects\HOGFW\templates\dlg.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item));
            
            #line default
            #line hidden
            this.Write("_collected then\r\n      public.get_");
            
            #line 82 "D:\work\Projects\HOGFW\templates\dlg.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item));
            
            #line default
            #line hidden
            this.Write("_prepare()\r\n      cmn.CallEventHandler( \"get_");
            
            #line 83 "D:\work\Projects\HOGFW\templates\dlg.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item));
            
            #line default
            #line hidden
            this.Write("\" );\r\n    end  \r\n");
            
            #line 85 "D:\work\Projects\HOGFW\templates\dlg.tt"
} 
            
            #line default
            #line hidden
            this.Write("    func_end()\r\n  end\r\n  cmn.CallEventHandler( \"dlg_");
            
            #line 88 "D:\work\Projects\HOGFW\templates\dlg.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(rmname));
            
            #line default
            #line hidden
            this.Write("_");
            
            #line 88 "D:\work\Projects\HOGFW\templates\dlg.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(dlgname));
            
            #line default
            #line hidden
            this.Write("_beg\" );\r\n  common_impl.dialog_character_loc = \"\";\r\n  common_impl.Start( \"");
            
            #line 90 "D:\work\Projects\HOGFW\templates\dlg.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(dlgname));
            
            #line default
            #line hidden
            this.Write("\", ");
            
            #line 90 "D:\work\Projects\HOGFW\templates\dlg.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(count));
            
            #line default
            #line hidden
            this.Write(", nil, nil, true, \"dlg_");
            
            #line 90 "D:\work\Projects\HOGFW\templates\dlg.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(rmname));
            
            #line default
            #line hidden
            this.Write("_");
            
            #line 90 "D:\work\Projects\HOGFW\templates\dlg.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(dlgname));
            
            #line default
            #line hidden
            this.Write("_func_end\", {  } );\r\nend;\r\n\r\n\r\n=============в секцию предмета============\r\n\r\nfunc" +
                    "tion public.get_");
            
            #line 96 "D:\work\Projects\HOGFW\templates\dlg.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item));
            
            #line default
            #line hidden
            this.Write("_prepare()\r\n  ObjAttach(\"spr_");
            
            #line 97 "D:\work\Projects\HOGFW\templates\dlg.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(rmname));
            
            #line default
            #line hidden
            this.Write("_");
            
            #line 97 "D:\work\Projects\HOGFW\templates\dlg.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item));
            
            #line default
            #line hidden
            this.Write("\",\"obj_");
            
            #line 97 "D:\work\Projects\HOGFW\templates\dlg.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(rmname));
            
            #line default
            #line hidden
            this.Write("_");
            
            #line 97 "D:\work\Projects\HOGFW\templates\dlg.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(dlgname));
            
            #line default
            #line hidden
            this.Write("_item\")\r\n  ObjSet( \"spr_");
            
            #line 98 "D:\work\Projects\HOGFW\templates\dlg.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(rmname));
            
            #line default
            #line hidden
            this.Write("_");
            
            #line 98 "D:\work\Projects\HOGFW\templates\dlg.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item));
            
            #line default
            #line hidden
            this.Write("\", {visible = 1, pos_x = 0, pos_y = 0} );\r\nend");
            return this.GenerationEnvironment.ToString();
        }
        
        #line 1 "D:\work\Projects\HOGFW\templates\t4helper.tt"

    void NeedComment(string message, bool comments)
    {
        Selector(comments,message,"");
        
        #line default
        #line hidden
        
        #line 5 "D:\work\Projects\HOGFW\templates\t4helper.tt"
}
    void Selector(bool selector, string messageTrue, string messageFalse)
    {
        string message = selector?messageTrue:messageFalse;
		if (message != "") {

        
        #line default
        #line hidden
        
        #line 10 "D:\work\Projects\HOGFW\templates\t4helper.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(message));

        
        #line default
        #line hidden
        
        #line 10 "D:\work\Projects\HOGFW\templates\t4helper.tt"

	}
}
        
        #line default
        #line hidden
    }
    
    #line default
    #line hidden
    #region Base class
    /// <summary>
    /// Base class for this transformation
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "16.0.0.0")]
    public class dlgBase
    {
        #region Fields
        private global::System.Text.StringBuilder generationEnvironmentField;
        private global::System.CodeDom.Compiler.CompilerErrorCollection errorsField;
        private global::System.Collections.Generic.List<int> indentLengthsField;
        private string currentIndentField = "";
        private bool endsWithNewline;
        private global::System.Collections.Generic.IDictionary<string, object> sessionField;
        #endregion
        #region Properties
        /// <summary>
        /// The string builder that generation-time code is using to assemble generated output
        /// </summary>
        protected System.Text.StringBuilder GenerationEnvironment
        {
            get
            {
                if ((this.generationEnvironmentField == null))
                {
                    this.generationEnvironmentField = new global::System.Text.StringBuilder();
                }
                return this.generationEnvironmentField;
            }
            set
            {
                this.generationEnvironmentField = value;
            }
        }
        /// <summary>
        /// The error collection for the generation process
        /// </summary>
        public System.CodeDom.Compiler.CompilerErrorCollection Errors
        {
            get
            {
                if ((this.errorsField == null))
                {
                    this.errorsField = new global::System.CodeDom.Compiler.CompilerErrorCollection();
                }
                return this.errorsField;
            }
        }
        /// <summary>
        /// A list of the lengths of each indent that was added with PushIndent
        /// </summary>
        private System.Collections.Generic.List<int> indentLengths
        {
            get
            {
                if ((this.indentLengthsField == null))
                {
                    this.indentLengthsField = new global::System.Collections.Generic.List<int>();
                }
                return this.indentLengthsField;
            }
        }
        /// <summary>
        /// Gets the current indent we use when adding lines to the output
        /// </summary>
        public string CurrentIndent
        {
            get
            {
                return this.currentIndentField;
            }
        }
        /// <summary>
        /// Current transformation session
        /// </summary>
        public virtual global::System.Collections.Generic.IDictionary<string, object> Session
        {
            get
            {
                return this.sessionField;
            }
            set
            {
                this.sessionField = value;
            }
        }
        #endregion
        #region Transform-time helpers
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void Write(string textToAppend)
        {
            if (string.IsNullOrEmpty(textToAppend))
            {
                return;
            }
            // If we're starting off, or if the previous text ended with a newline,
            // we have to append the current indent first.
            if (((this.GenerationEnvironment.Length == 0) 
                        || this.endsWithNewline))
            {
                this.GenerationEnvironment.Append(this.currentIndentField);
                this.endsWithNewline = false;
            }
            // Check if the current text ends with a newline
            if (textToAppend.EndsWith(global::System.Environment.NewLine, global::System.StringComparison.CurrentCulture))
            {
                this.endsWithNewline = true;
            }
            // This is an optimization. If the current indent is "", then we don't have to do any
            // of the more complex stuff further down.
            if ((this.currentIndentField.Length == 0))
            {
                this.GenerationEnvironment.Append(textToAppend);
                return;
            }
            // Everywhere there is a newline in the text, add an indent after it
            textToAppend = textToAppend.Replace(global::System.Environment.NewLine, (global::System.Environment.NewLine + this.currentIndentField));
            // If the text ends with a newline, then we should strip off the indent added at the very end
            // because the appropriate indent will be added when the next time Write() is called
            if (this.endsWithNewline)
            {
                this.GenerationEnvironment.Append(textToAppend, 0, (textToAppend.Length - this.currentIndentField.Length));
            }
            else
            {
                this.GenerationEnvironment.Append(textToAppend);
            }
        }
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void WriteLine(string textToAppend)
        {
            this.Write(textToAppend);
            this.GenerationEnvironment.AppendLine();
            this.endsWithNewline = true;
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void Write(string format, params object[] args)
        {
            this.Write(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void WriteLine(string format, params object[] args)
        {
            this.WriteLine(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Raise an error
        /// </summary>
        public void Error(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Raise a warning
        /// </summary>
        public void Warning(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            error.IsWarning = true;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Increase the indent
        /// </summary>
        public void PushIndent(string indent)
        {
            if ((indent == null))
            {
                throw new global::System.ArgumentNullException("indent");
            }
            this.currentIndentField = (this.currentIndentField + indent);
            this.indentLengths.Add(indent.Length);
        }
        /// <summary>
        /// Remove the last indent that was added with PushIndent
        /// </summary>
        public string PopIndent()
        {
            string returnValue = "";
            if ((this.indentLengths.Count > 0))
            {
                int indentLength = this.indentLengths[(this.indentLengths.Count - 1)];
                this.indentLengths.RemoveAt((this.indentLengths.Count - 1));
                if ((indentLength > 0))
                {
                    returnValue = this.currentIndentField.Substring((this.currentIndentField.Length - indentLength));
                    this.currentIndentField = this.currentIndentField.Remove((this.currentIndentField.Length - indentLength));
                }
            }
            return returnValue;
        }
        /// <summary>
        /// Remove any indentation
        /// </summary>
        public void ClearIndent()
        {
            this.indentLengths.Clear();
            this.currentIndentField = "";
        }
        #endregion
        #region ToString Helpers
        /// <summary>
        /// Utility class to produce culture-oriented representation of an object as a string.
        /// </summary>
        public class ToStringInstanceHelper
        {
            private System.IFormatProvider formatProviderField  = global::System.Globalization.CultureInfo.InvariantCulture;
            /// <summary>
            /// Gets or sets format provider to be used by ToStringWithCulture method.
            /// </summary>
            public System.IFormatProvider FormatProvider
            {
                get
                {
                    return this.formatProviderField ;
                }
                set
                {
                    if ((value != null))
                    {
                        this.formatProviderField  = value;
                    }
                }
            }
            /// <summary>
            /// This is called from the compile/run appdomain to convert objects within an expression block to a string
            /// </summary>
            public string ToStringWithCulture(object objectToConvert)
            {
                if ((objectToConvert == null))
                {
                    throw new global::System.ArgumentNullException("objectToConvert");
                }
                System.Type t = objectToConvert.GetType();
                System.Reflection.MethodInfo method = t.GetMethod("ToString", new System.Type[] {
                            typeof(System.IFormatProvider)});
                if ((method == null))
                {
                    return objectToConvert.ToString();
                }
                else
                {
                    return ((string)(method.Invoke(objectToConvert, new object[] {
                                this.formatProviderField })));
                }
            }
        }
        private ToStringInstanceHelper toStringHelperField = new ToStringInstanceHelper();
        /// <summary>
        /// Helper to produce culture-oriented representation of an object as a string
        /// </summary>
        public ToStringInstanceHelper ToStringHelper
        {
            get
            {
                return this.toStringHelperField;
            }
        }
        #endregion
    }
    #endregion
}
